### ISSUE TITLE
[Mono] RouteViewer Colored Rail Path Form, Display Checkbox not working

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#1025]
### Description

When unchecking the Display checkbox like so:
![image](https://github.com/leezer3/OpenBVE/assets/28094366/b1914433-edc9-48e3-b0ae-8dde34f28bf6)

Nothing changes, and when opening again all Display are checked again.
It seems `CurrentCellDirtyStateChanged` is not fired under mono at all, which means the track display won't be updated.

### Related information 

* Operating system: Debian Trixie
* Method of control: Keyboard

**Comment by ginga81** [comment]
From the beginning, Linux is designed to not update in real time unless you close the window, unlike Windows.
I also asked about it when it was implemented, and I think leeser3 would reply, but he said that it wasn't possible on Linux.

**Comment by Kenny-Hui** [comment]
Problem is it doesn't update when you close the window either :P
Although this is most definitely a mono issue

**Comment by leezer3** [comment]
Unfortunately, the short answer is that WinForms on Mono has a bunch of unexplained bugs, and has been officially abandoned.

This appears to work for me, so it's likely timing related.
Try the build from today, which adds a hacky workaround.

FWIW, concurrent drawing on Linux of a GL window and a Winform from the same process is near enough impossible to get to work correctly. (I've tried first in BVEC_ATS and then in OpenBVE)
The Mono Winforms code seems to require being in control of the main window update / paint loop, otherwise it throws a wobbly.
Adding in **Application.DoEvents()** calls everywhere makes things work marginally, but if one thread stalls, the other whites out.

**Comment by Kenny-Hui** [comment]
Works as of the latest nightly build, thanks
