### ISSUE TITLE
[Bug] Strong freezes when changing between cameras

### ISSUE THREAD

**Issue by hotdamndel** [leezer3/OpenBVE#1044]
Switching camera views on reasonably detailed trains causes a large lag spike (apparently when models are loading). Can provide sample trains if needed.

**Comment by ginga81** [comment]
Indeed, when I press F2F3 to switch between the E5+E6 and E2 series Shinkansen trains that I created together for the first time after loading them, it takes 3 to 4 seconds for them to display.
I think this has been happening since OpenBVE switched to the new drawing method (not OpenGL, but the method that displays Routeviewer simultaneously and sequentially around 1.9).

**Comment by leezer3** [comment]
Now that's interesting.
It's loading the textures into memory that causes the freeze (turn on Load in Advance to workaround this)

The threading changes seem to have broken an older workaround, which basically just showed and hid the exterior as the game was loading.
I think this probably needs a bit of redesign around textures which must be pre-loaded.

**Comment by leezer3** [comment]
Should now be fixed with the build from today.

You'll see slightly longer load times (as all player train textures are now pre-loaded), and all player train textures are disallowed for unload.
