### ISSUE TITLE
Cannot play BVE5 routes in new versions of openBVE

### ISSUE THREAD

**Issue by soyachoin104** [leezer3/OpenBVE#1088]
I recently downloaded the 8th November nightly build and for some reason, I cannot seem to play BVE5 routes in openBVE anymore. The game remains stuck on the "Processing route" page. I am able to select a train, but when I click start, the screen just freezes, and I can only close it with Task Manager. I also thought maybe openBVE just takes longer to process these routes but after waiting 25 minutes, nothing happened. 

I have done a full reinstall of the game, tried backdating to older versions but the issue continues to occur. I think it is probably a problem on my end but I'm not sure as to what could be occurring. 

This has been a problem with every BVE5 route in my archive, the game operates as normal with standard openBVE/BVE4 stuff. 

I'm a Windows 11 user, my openBVE directory is in the C:\ProgramFiles (x86)\openBVE 

I'm not entirely sure what could be the cause of this issue, there are no logs generated as the game doesn't make it past the route/train select screen.

**Comment by leezer3** [comment]
I've found the issue, and it's I'll admit not one I'd thought of...

Some routes seem to use negative track positions, which by the looks of things BVE5 handles OK.
A bunch of the speedups done were (essentially) to actually use the distance as the block key, rather than using LinQ to find the key within the array, which is rather slow, and this hadn't taken into account negative track positions.
