### ISSUE TITLE
64-bit builds

### ISSUE THREAD

**Issue by yuuka-miya** [leezer3/OpenBVE#155]
Would 64-bit builds help in any way towards letting us build and run more detailed routes?

**Comment by leezer3** [comment]
Short answer is not really.

@Sirflankalot has a renderer re-write underway here:
https://github.com/Sirflankalot/OpenBVE/tree/new_renderer

This will increase FPS, and as a consequence will allow more detailed objects.

Longer answer:
There are considerably more problems with the current state of play that 64-bit simply won't address.
The largest issue is with the route loader- When a route is loaded, each object is cloned and placed induvidually into memory at the start of the simulation.
Whilst 64-bit would marginally help here, that's essentially a case of adding a sticky-plaster to a massive wound. The loading routines need to be re-written to a more conventional 'tiled' or similar setup, so that only the visible portion of the world is loaded and resides in memory at any given time.

If you dig into the code, you'll find there are a lot of situations like this. There have also been a lot of 'assumptions' made (e.g. that all trains within the world are identical) , which mean that making a seemingly small change requires a lot of behind the scenes work.

Things are slowly being changed, but this is not a quick process.

**Comment by Sirflankalot** [comment]
Following up on what @leezer3 said, we have really big issues that need to be fixed. We essentially have a very slow renderer from the 2000's and then we're surprised when it can't deal with a couple million polygons. This rewrite is in progress and should start to be properly implemented soon. 

Systemic change is needed and that takes a long time because we want to do it right this time. Figuring out the use cases profiling, rewriting, vetting, is a very long process when it has the possibility to break the entire game. Have faith, it is coming a long, but there are a long list of things that need to be redone:

- Renderer
- Route Parsing
- World Handling
- World Editing
- And more

We all have pipe dreams about features that OpenBVE will be able to support and it will get there, but it'll be a lot of elbow grease to get it there.
