### ISSUE TITLE
Allow to overwrite default ATS sounds

### ISSUE THREAD

**Issue by City-busz** [leezer3/OpenBVE#171]
Currently it's impossible to overwrite file names of the ATS sounds when the default ATS plugin is used, because it calls LoadDefaultATSSounds unconditionally:
https://github.com/leezer3/OpenBVE/blob/262183c714c735178ec86b6a4ac41fff512636c0/source/OpenBVE/OldCode/PluginManager.cs#L508

So when I want to define sounds for the default ATS plugin in sound.cfg, it simply ignored:
```
[Ats]
0 = ats.flac
1 = atscnt.flac
2 = ding.flac
3 = toats.flac
4 = toatc.flac
5 = eb.flac
```
I think the best would be to merge SoundCfg.Ats.cs into SoundCfg.Bve2.cs, and load ATS sounds in the same way as other sounds.

**Comment by leezer3** [comment]
Good spot.

However, it might not be quite that simple, I'm going to have to think about this one a little.....

The current behaviour means that the ATS sounds in sound.cfg will always be ignored with the default plugin, which obviously a bug.
However, I'm not entirely certain that no-one is relying on this to load the 'correct' sounds, and so I'm reluctant to just fix this out of hand; This is just the sort of undefined behaviour that comes back to bite you.....

Looking at the code, I also suspect that moving plugin loading to before sounds (hence allowing us to easily check if the plugin is 'default' or not) will cause them to go nuts when the trains are moved during the loading process.

**Comment by City-busz** [comment]
I created a PR, but yes, it breaks trains that have sound.cfg, but don't define the ATS sounds.

**Comment by leezer3** [comment]
Yeah, I get the horrible suspicion that this will end up breaking something somewhere......

I think the best (of a bad bunch) is going to be to do the following:
Add a call to load the default sounds before the sound.cfg is loaded, e.g. https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/Parsers/SoundConfiguration/SoundCfg.Base.cs#L14

This then allows them to be overwritten by the load call if required, but doesn't stop them being found.

The other option would be to keep things as-is for the existing formats, but remove this behaviour for **sound.xml** , so that any plugin sounds used here must be defined.

Obviously, using a new format means that your users must have the correct program version, but it maintains backwards compatibility.

**Comment by City-busz** [comment]
I created another PR to support the old behaviour but allow to override file names.

**Comment by leezer3** [comment]
For future reference, an errata note has been added here:
https://github.com/leezer3/OpenBVE/wiki/Errata#default-plugin-ats-sounds
