### ISSUE TITLE
Implement Mechanik Parser/migration tool for OpenBVE 

### ISSUE THREAD

**Issue by afarlie** [leezer3/OpenBVE#209]
BVE Cornwall has a small number of ancient routes for Mechanik, which no longer runs easily on some modern systems.  

It would be nice to have a way to render/play the small number of existing legacy routes in a modern simulator like OpenBVE,

**Comment by Sirflankalot** [comment]
I am currently working on a project that will include tools for easy modernization of routes. I only just encountered these old Mechanik routes, but they are definitely on my todo list for this project. Though, I don't want to get too ahead of myself and say dates.

**Comment by MarcRiera** [comment]
I was actually thinking about Mechanik routes in OpenBVE a while ago, and the format is well-documented. It's messy, it's stuff from 20 years ago, but there are only a few commands. There's an old but great German website with a small tutorial on how to develop Mechanik routes: http://mechanik.peterulrich.de/trasa.html (it's in German, but I've managed to follow it using machine translation).
The Mechanik format has the advantage of being based on the player's rail just like BVE. Curves aren't used frequently because the rotation had to be calculated manually by the route developer, but it shouldn't be too difficult to generate radius values from offset values. The disadvantage of the format is that the concept of 'object' (as in BVE) doesn't exist; textures are placed directly. I guess a good idea for a Mechanik to BVE converter would be to generate an object for each texture declaration, and then check for duplicates.
While I'm not 100% sure I could be able to write such a converter myself, I'm quite familiar with Mechanik and I could do some testing and reverse engineering to at least write proper documentation for the trasa.dat format.

**Comment by Sirflankalot** [comment]
That's a lovely bit of documentation and from the looks of it the machine translation did perfectly fine. 

That texture issue seems like an issue from the outside but it really wouldn't be a problem at all. Your method would be easy to implement and fast. 

> While I'm not 100% sure I could be able to write such a converter myself, I'm quite familiar with Mechanik and I could do some testing and reverse engineering to at least write proper documentation for the trasa.dat format.

This would be **AMAZINGLY** helpful for getting this kind of thing implemented.  If I had proper documentation for it, I could possibly roll a parser in a couple days. Still wouldn't be the highest thing on my TODO list, but it would get done.

**Comment by leezer3** [comment]
This is as close to official documentation as there ever was (Czech, although Google translate doesn't auto-detect it for some reason):
http://mechanik.wz.cz/edit/soubory.php

I've briefly played with this in the past, but haven't got anything to a reasonably working stage.

Caveats:
* Object sizing is a PITA. Perpendicular planes set the top left point, and then calculate the size of the face from the texture dimensions. All other face types use a standard vertex declaration.
* Axis are marginally non-standard as follows, and are centered on approx 0,2,0 [Driver's eye point]:
X - Positive values to the **RIGHT**
Y- Positive values **BELOW, not above**
Z- Positive values in **FRONT**
* Z-sorting is performed in the order that planes are declared
* Due to the Z-sorting noted above, object visibility is an issue, as it's declaring small objects sometime with a center 500m away from the actual faces in use, and the BVE renderer wasn't really setup for that. It essentially needs the objects translating back to be centered on 0,0,0 & the world adjusting somehow.

**Comment by Sirflankalot** [comment]
I don't think we necessarily need to preserve z-sorting. As long as we can get the position, let normal positional based z-sorting do it's job, or just let the Z buffer do its thing and we're done. I don't think there is necessarily a problem with z-sorting being different. Maybe I'm not quite understanding.

That's a strange modified left-handed coordinate system. Conversion should be trivial.

**Comment by leezer3** [comment]
You can set a vertex at which the object disappears (Last parameter, divide by three for some unknown reason), which I don't think necessarily has to be part of the face.

If I recall, this essentially sets two faces into an identical position in the world, with the first Z-sorted into the front, which then disappears for a sorta primitive animation effect.

This is taking me back :p

**Comment by Sirflankalot** [comment]
Haha!

Methinks it can be simulated with an animated object with proper function scripts. So that way we are actually doing what is intended. I'd have to think more about the specs to know for sure, but it sounds  like it would work.

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/tree/Mechanik

That's a semi-functional parser for Route Viewer only based upon my previous hacking around and some more twiddling over the last couple of days.
### Issues:
* Block disposal is currently rather broken. In practice, this means the first 1km of any route is OK (Well ish....), but it then doesn't load the next block correctly until it is entered. The object from the first block also appear to be appearing there (??? I suspect an assumption on block lengths causing an arithmetic overflow somewhere ???)
* Object loading is a total hack job; For testing, it was easier to just mod the B3D parser to accept a string array and generate one on the fly than writing it all over again.
* I really don't know why you need to multiply the texture size by 5 to get the actual size for __'s__ objects. Probably made some sort of error somewhere.....
* Nothing other than basic objct 

![m1](https://user-images.githubusercontent.com/7688245/34363457-359c9014-ea74-11e7-948d-9c7c7553c576.jpg)

**Comment by MarcRiera** [comment]
Despite the bugs and glitches, this looks great! I have compiled this modified RouteViewer but I haven't managed to load any of the routes in BVE Cornwall, I just get a bunch of errors related to Tekstury.dat (where textures are defined).

I've been trying to manually recreate part of one of the routes as a big CSV object and except scaled textures and the Z-sorting thing I haven't found anything overly complicated. Everything is pixel-based and looks confusing at the beginning, but in the end it makes sense.

I think I now understand how textures are applied to a face. Basically, four elements are taken into account: the texture dimensions, the "scaling" value and the two "vector" values. Textures are not stretched by default (unlike BVE); faces are filled with textures keeping their aspect ratio and dimensions. For example, the default track texture is 32x32 pixels. In a track face with a size of 4x100 metres (800x20000 pixels), with a scaling factor of 1, the texture would be repeated 25x625 times to fill the face. If the scaling value were 25, Mechanik would act as if the texture were 25 times bigger (800x800 pixels), and the texture would be repeated 1x25 times. The vector values seem to alter the texture before it is applied by scaling several dimensions; the same 32x32 texture would be treated as if it were 64x32 with a horizontal "vector" set to 2 and a vertical "vector" set to 1. This is how textures can be stretched.

I've got no idea about why scaled textures always need an initial scale of 5 to display correctly, but it definitely isn't your mistake, my converted textures were too small with the default size too. It's one of Mechanik's weird things. Also, keep in mind that everything will have to be moved a bit to the right and up to fix the driver position offset.

**Comment by leezer3** [comment]
Hmm, try again with the current commit from that branch :(
That fixes the issue of nothing whatsoever loading, plus makes the compatibility a little better.

Haven't dealt with the texture scaling or anything complicated at the minute.

**Comment by leezer3** [comment]
Texture scaling is proving to be a right pain :S

Have pushed another commit to the mechanik branch that helps in standard horizontal cases (e.g. trackwork, grounds and stuff), but has issues with other stuff.
Main issue is that we don't know beforehand where the face points are positioned (Other than that they're declared CW), and it's being a PITA to select the correct distance for calculations.

**Comment by leezer3** [comment]
OK, latest commit fixes most of the visibility issues, although there are still the occasional glitches with objects at silly (1.5km from origin plus) distances, as Mechanik now uses a 1.5km as it's visibility distance. This handles most stuff, as we seem to have a normal block-length of ~500m.

Next move is to implement something which moves objects automatically so that they're as close to 0,0,0 as possible to remove the rest of these glitches.

To fix / implement:
- Various texture scaling glitches
- Diagonal faces will need trig to calculate the length of the face, not the distance between the Min/ Max values.....
- Curves
- Sounds
- Signals
- Panels (??)

**Comment by leezer3** [comment]
![m2](https://user-images.githubusercontent.com/7688245/34439884-1f1f4296-eca9-11e7-8b9c-b3e58829fdf8.jpg)
![m3](https://user-images.githubusercontent.com/7688245/34439885-20c7855e-eca9-11e7-8afb-6f7a35783ee4.jpg)

Couple of screenies.

**Comment by leezer3** [comment]
Latest commit makes the **FirstPoint** variable work, and fixes (most) of the texture scaling issues on non-diagonal faces.

Will try and add signalling and stations next. Curves may need some work, need to investigate exactly what the correction factors do.

**Comment by afarlie** [comment]
Thanks for the effort so far on this, I hadn't expected such rapid progress :)

**Comment by leezer3** [comment]
Been revisiting this over the last few days:
https://github.com/leezer3/OpenBVE/tree/mechanik_plugin

![2020-11-14 14-15-58(1)](https://user-images.githubusercontent.com/7688245/99149287-e71e6700-2684-11eb-8102-e4a21f7f1b92.gif)


Basic changes:
* Converted to a plugin.
* Curves are now working to a certain extent (Basic curves and small pointwork works OK, haven't tried to figure out the correction factor command yet for large-scale curves)
* Sound events partially working.
* Speed limits working (no display, which is an issue, going to have to add a message when it changes I think)

**Comment by leezer3** [comment]
A little more bashing, and the linked new branch now has speed limits, stations & will load and drive in the main sim.
Track layouts work, but due to the correction markers not being implemented, the offset is off.

Sounds have been added (and show up in the events overlay) but don't seem to work.
Need to investigate.

### Primary mising features / issues at this point:
* Correction markers for use after a curve. 
* Signalling
* Still some glitchy faces
* Fixing sound issues

Either way, this is making some progress now :)

**Comment by leezer3** [comment]
Correction markers now fixed in the linked branch, along with some incidental other improvements to the other plugins to eliminate so many cases of passing an unused null transform.

(n.b. This may not work perfectly with all correction markers, but it does with my limited test set)

Primary issue is now the glitchy faces.
There's also the slight problem that the cab clouts the overhead on most routes if this is present. (As BVE cabs are assumed to have a drivers eye viewpoint different to that of Mechanik) & the fact that Mechanik track is flat 2D faces on the ground.
Easiest solution to this is likely to be to add a 30cm (?) vertical offset to all objects, but will look at that in detail at some other stage.

**Comment by leezer3** [comment]
A little more work done today (Primarily just adding errors and documentation to what I've already done), will be doing more over the next week or so.

Not sure correction markers are quite right yet, but they're *nearly* there, and OK for a lot of stuff.
Most glitchy faces seem to be diagonal.
I get the nasty suspicion that they're rotated to straight before trying to calculate the texture co-ordinates (or something similar...)

**Comment by leezer3** [comment]
For anyone interested, I've now opened a PR to implement this plugin.
Testers welcome :)

Textures are fixed properly (required projecting the point vector onto the first point vector to find the length, headache...), and our biggest missing feature is now the signalling.

With this plugin built (and the other required changes from the PR),  Mechanik routes are now relatively close to usable.

My intention is to merge this in the next few weeks relatively as-is. 
Fine-tuning can then be carried out at a later date.

**Comment by leezer3** [comment]
Signal Aspect to texture mapping tables:

## Type 1:


| | 0 | 1 | 2 | 3 | 4 | 5 |
|---|---|---|---|---|---|---|
|**0**|80|80|80F83|80F83|80|80|
|**1**|80|80|80|80|80|80|
|**2**|80|88|88F92|88F92|87F92|86|
|**3**|80|89|89F91|85F90|87F91|87|
|**4**|80|85|85F90|85F90|94F90|84|
|**5**|82|80|80|80|80F82|80|

**Key:**
Number represents the texture from *tekstury.dat* shown to the corresponding aspect pairs- Aspect 1 from the top row & Aspect 2 from the first column. 
Two numbers separated by a F corresponds to a flashing set of textures, ~1 second flash interval.

**Comment by leezer3** [comment]
Signalling is in and seems to work. Station events need fixing (start and end reversed & some odd errors, must have made a typo somewhere), and the station related ones need to be hooked in.

At the minute, the AI will vey happily drive a Mechanik route, and most things work reasonably,

**Comment by leezer3** [comment]
Discovered today that Mechanik seems to issue an undocumented correction at each 2km tile boundary.
Adding this makes the IRT-NY route drivable, and may also fix glitches in other routes I've not yet discovered / noticed.

The plugin in the linked PR is now largely usable.
There's still a slight visual glitch after a large correction (Mechanik sometimes has a small one, this is a little larger), but it's now largely ready for real-world use.

**Comment by leezer3** [comment]
## Route generator documentation:
Partial files contain two control comments. At the minute, I'm presuming these must be the first two lines,

```
//*dlugosc 2
```
Number is the length (in 2km tiles) of this module.
```
//*stacja 0
```
Number is the number of stations present in this module.

### GEN_1_93.exe
Asks for a route length from 0- 99km
Asks whether the route should be stopping or direct.
Reads **MODULY.DAT**
This must have the following section headers:
```
//stacje jednotorowe poczatkowe
//stacje dwutorowe poczatkowe
//szlak jednotorowy
//szlak dwutorowy
//switche 1->2
//switche 2->1
//stacje koncowe jednotorowe
//stacje koncowe dwutorowe
```
Translated for reference:
```
// single-track starting stations
// two-track starting stations
// single track trail
// double track
// switches 1-> 2
// switches 2-> 1
// single-track end stations
// two-track end stations 
```

From there, it'll create a random set of appended dat files. 
Unclear without reversing the thing exactly what the rules are, but we can probably do something like this to produce a reasonable facsimile:
1. Choose starting station, 1 or 2
2. Add random number of modules (say 1 - 4)
3. Add second station
4. Repeat as required
5. Add end station

Further thoughts:
* If the routefile generator was to be implemented in the main game, hide all dats listed in the MODULY.DAT
* Again, unclear as to which stations should have a stop, but this could easily be fudged.
* Alternate texture sets are sometimes found in ZIP sfx files. I'm sure I remember a text based menu launcher that controlled these, but can't see it in the archives.....
* Related to the above: Probably relatively easy to hook / extract these as part of any generator implementation?!
* Some files don't ship the default textures. May be worth just adding all of these as part of the compatability folder.
