### ISSUE TITLE
Issues with Side Signs on R44/46

### ISSUE THREAD

**Issue by PieSuperPAC** [leezer3/OpenBVE#215]
The side signs on the R44 and R46 disappear unless the camera is very close to them in BVE 1.5.3.

Images for reference:
![image](https://user-images.githubusercontent.com/35183207/34898201-c8c9ced0-f7bf-11e7-8836-5252ee8ce09d.png)
![image](https://user-images.githubusercontent.com/35183207/34898230-f009d3a0-f7bf-11e7-91e8-5d5aac3c571c.png)
My settings:
![image](https://user-images.githubusercontent.com/35183207/34898247-0a564ad6-f7c0-11e7-9136-fb187dc71ee2.png)

**Comment by leezer3** [comment]
This is being caused by the way the signs have been written, and there isn't a lot that can be done about it.

The text layer for the signs is created using an image, a sample of which is shown here:
![a207](https://user-images.githubusercontent.com/7688245/34906549-b54349e2-f867-11e7-9085-2518c40dde97.png)

This uses transparency to overlay the image onto the actual window, and then uses the texture shift function to move it.

When ansiotropic filtering (or most of the other texture filtering options) are turned on, openGL first resizes the texture, and then blends the pixels to create the smoothest possible texture. In this case, the text is simply getting 'blurred' out as the camera gets further away from it, and the relative text size gets smaller and smaller.
To make this work correctly, the textures need to be re-written to not use transparency, as this is blended differently.
