### ISSUE TITLE
Some X files fail to read

### ISSUE THREAD

**Issue by s520** [leezer3/OpenBVE#277]
### Description

When the X file that is from the Metasequoia LE R3.0 exporter, it cannot read by OpenBVE, ObjectViewer and RouteViewer.

At the ObjectViewer, that is error with "Unexpected semicolon encountered in template Mesh in textual X object file filename.x".

At the first common point of failing read X files, the header that is "xof 0302txt 0064".

Second, at the before starting of 'Material' section, there are two semicolons exists.

In addition, if remove one of a semicolon, X file can read successfully.

` MeshMaterialList {` 
`   1;` 
`   1;` 
`   0;;` 
`   Material {`

In my judgement from error result, I think that relation of "source\ObjectViewer\Parsers\XObjectParser.cs", line 398-405.

### Reproduction

Please check it the attached sample X file.
[cannot-read-x.zip](https://github.com/leezer3/OpenBVE/files/2415039/cannot-read-x.zip)

## Route

No dependency of Route file.

## Train

No dependency of Train file.

## Logs

Unexpected semicolon encountered in template Mesh in textual X object file C:\Users\User\Desktop\cannot-read-x\aaaa.x

### Related information 

We have checked with these Operating systems.

- Windows 8.1 64bit
- Ubuntu 16.04.5 LTS with mono 5.14.0.177

This issue was translated by Midnight Express Ginga81(ginga81). I really appreciate it.

**Comment by leezer3** [comment]
Unfortunately, the X parser is a total mess, which I've had very little to do with.

It's tripping up here:
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/Parsers/Object/Generic/XObjectParser.cs#L401

Changing the two lines to the following will fix your example:
```Position++;
continue;```

I'll need to hunt out the file this hack was added for, but I have the nasty suspicion that this was in the top **Template** section, rather than inlined within a mesh.

Let me do some more testing and see if that change breaks anything.

It's also on my list to re-write the X parser considerably, but somewhere rather too low down it.....

**Comment by s520** [comment]
When examining the value of the variable with the debugger, s was ";Material".
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/Parsers/Object/Generic/XObjectParser.cs#L370
So, changing the three lines to the following fix our example.
```
Position++;
i++;
continue;
