### ISSUE TITLE
train cabs not loading

### ISSUE THREAD

**Issue by oddpodlbkk** [leezer3/OpenBVE#309]
### Description

select cabs of some trains will not load all of the textures, or wont load the cab at all

## Route
https://www.bvestation.com/download/339 (F)

http://openbveconnect.com//index.php?action=downloads;sa=view;down=63 (C)
## Train
https://drive.google.com/file/d/1t76kesY8axkqgwy4Ud9JkBkETuy9qU4d/view?fbclid=IwAR3xhnjHKhh1uOiES7TgGZKD-xMO29x372VYSH0XdeJnERrk94HskrEh_3o (R46)

http://www.mediafire.com/file/sw5yw8qdlaxz38c/R143_%2528Bombardier%2529_%2528New_Brakes%2529.zip/file (R143)
## Logs

[log.txt](https://github.com/leezer3/OpenBVE/files/2846828/log.txt)

### Related information 
using Raildriver, running on Windows 10 in full screen(Windowed mode does not have an effect)

**Comment by s520** [comment]
The OpenBVE log exists in the following path, so I think that it is better to upload it again.
`C:\Users\<username>\AppData\Roaming\openBVE\Settings\log.txt`

**Comment by oddpodlbkk** [comment]
[log.txt](https://github.com/leezer3/OpenBVE/files/2847180/log.txt)

**Comment by leezer3** [comment]
Will try and take a look tonight.

Most of the NYC content is an interdependant mess though.
Are you sure it's not calling for stuff from another route / train pack?

**Comment by leezer3** [comment]
Neither appears broken to me- Only thing I can see is some developer errors, which need to be fixed at their end really.

### R46
The positioning of the cab objects is wrong- They should be ~1m further forwards.

This is because the center of the cab (e.g. 0,0,0 in the base object) should be where the center of the driver's eyes are.
If you move the camera backwards slightly, you'll find the cab as expected.

There are also a couple of transparency issues.

This has exactly the same problems in 1.4.3, so it's definitely nothing done by me.



### R143
I can't see anything wrong here at all.
The cab only uses three animations (speedo digits, door L and door R), all of which are present.

### Other Notes
The R46 contains both a 2D and a 3D cab-
The 3D cab will always take precedence.

If you're seeing something you think is specifically broken, any chance of a screenshot?

**Comment by leezer3** [comment]
Have added a couple of marginal improvements to the way the R46 and anything with similar issues are handled, but this won't affect things, just make the log clearer / neater as to what's going on.

**Comment by oddpodlbkk** [comment]
the issue with the r143 is apparent in some routes, but when it happens, only shows the speedo. ill see if i can fix the R46 with that info

**Comment by leezer3** [comment]
I can't think why the issues with the R143 would be routefile specific; I think it's far more likely to be symptomatic of the whole raft of issues with the NYCTA stuff in general.

My best guess at the minute would be that you're simply running out of memory available at times;
32-bit .Net can only allocate ~3gb of memory and the NYCTA stuff runs perilously close to this. The train is loaded last, and so glitches here would be the last thing I'd expect before hard crashing.

If you've got a routefile which reliably reproduces it, I can certainly take a closer look, but the root issues with the NYCTA stuff need addressing first.
Some brief examples:
* The exterior for the R143 uses textures which are somewhere around 2- 3 times the size they need to be. For bonus points, they don't even comply with the power of two rule.
* Similar issue in the R46, both exterior and cab.
* The R46 has multiple copies of sounds all over the shop, unused files, the works....
* The R46 speedo uses 55 states to run a simple 2-digit speedometer (ouch). This could be done with 2 objects and a texture shift function far more efficiently.

I'm halfway tempted to produce an optimised version of the R46 just to see what it does to the framerate / load times....
