### ISSUE TITLE
Suggestion of the plug-in to incorporate in the Route

### ISSUE THREAD

**Issue by s520** [leezer3/OpenBVE#316]
This time, we suggest plug-in to incorporate in the Route. We call this plug in "Route plug-in". First, this will enables the following things:

- Reproduction of functions of ATC-2, which formerly used in Japanese Tohoku-Shinkansen. e.g. displaying 275 km/h-signal by replacing 240 km/h-signal in some train.
- High-Speed Proceed (Green Green) signal for certain train.  If it is not a corresponding vehicle, High-Speed Proceed signal will not indicated.

It absorbs the difference between individual vehicle plug-ins, and if it is the same security device, it can correspond with one route file. Currently, if differences exist in specifications even in plug-ins that reproduce the same security device, conventionally it was necessary to separate the route files. Route plug-in resolves this problem by receiving information from the vehicle plug-in and converting the signal index, Beacon index, etc.

The documentation of the plug-in is as follows.
https://5c6ab2a48710ca000baa7514--openbve-japan.netlify.com/en/plugins/iruntime2.html

Source code is here.
https://github.com/s520/OpenBVE/tree/RoutePlugin

Next, I will explain about sample data.

In order to operate this sample data, following data

- Midnight Express Ginga 81's とーほぐ新幹線v0.09 (http://midnightexpginga81.web.fc2.com/touhoku_shinkansen/index_touhoku.html)
- F81 tec200's Series-E4 Shinkansen train (https://www.youtube.com/watch?v=-bjdICkOPD0)
- Main program: [OpenBVE-RoutePlugin_bin2.zip](https://github.com/leezer3/OpenBVE/files/2875820/OpenBVE-RoutePlugin_bin2.zip)
- Plug-in: [OpenBVE-RoutePlugin_test_files.zip](https://github.com/leezer3/OpenBVE/files/2875804/OpenBVE-RoutePlugin_test_files.zip)

Move contents as follows: 
- Contents of the Tec_E4 folder to the F81 tec200's Series-E4 Shiinkansen folder.
- Contents of the とーほぐ新幹線v0.09 folder to the Midnight Express Ginga 81's とーほぐ新幹線v0.09 folder.

NOTE:

- ATCFS in the Tec_E4 folder is for testing corresponding to this new specification. An error will occur when reading with normal version of OpenBVE.
- The Route file of the とーほぐ新幹線v0.09 folder is just adding the description of "Route.Plugin RouteAPI.dll" on line 15.

The testing item is shown below.

1. converting the signal index automatically.
At the atcfs.cfg, change to "AtcType = 0" on purpose.
This is meaning namely for ATC-1 mode.
When we are attempt to drive at this setting, the signal system which is mismatch, but the signal shown to ready to drive.
In this case, in spite of must not drive, we can drive it.
At this route plugin, the signal index set to zero when signal system is without set for ATC-2.
So, it is impossible to drive, and prevent runaway.

2. converting the Beacon index automatically.
Please change "AtcType = 0" to "AtcType = 4" at atcfs.cfg. (DS-ATC mode)
At this route plugin, when the signal system setting is "AtcType = 4",at the route file line 1041, convert from ".beacon 4;0;-1" to ".beacon 90;0;1".
".beacon 90;0;1" is a command which is change the signal system to ATC-2.
So, if the convert is successfully, mismatch to the case of 1., as a result, the signal is shown normally.

This sample is so simply, but this plugin can do such as this example.

When we developed the plugin's specification, it is more difficult to change later.
So,Before the create pull request, we want to have a discuss about this with Mr.leeser3.
After the discussed, we will develop the plugin's specification.
Please consider about it.

This post was translated by F81 tec200 and Midnight Express Ginga 81. I really appreciate it.

**Comment by leezer3** [comment]
Interesting concept.

My initial thought though would however be to implement any logic wherever possible into the main program rather than a complicated set of plugins communicating backwards and forwards.
I don't necessarily think your reasoning is wrong, but that perhaps more that you're approaching this from a different direction than I would.

Both of your examples seem to me that the 'better' way to do this would be for the train plugin to report to the main program which safety systems it supports.
They also expose the limitations of the current beacon / signalling system, in that there's no standardisation between plugins or routes, and I suspect run the risk of unintended consequences when running an unusual route / train combo.

Perhaps this would be a better structure:

1. Add in interface whereby a train plugin reports which safety systems it implements.
2. Similarly, replace the Route.Change with a specification which reports which systems are implemented by the route.
3. Create a replacement for the .beacon command, which supports multiple transmissions depending on which safety system the train reports as supporting.

This however has the issue that it'd break, or at least make more difficult legacy plugin based trains (which are obviously the majority of stuff, and will probably continue to be so).
The 'new' standard could be relatively easily set to transmit the legacy beacons depending on the plugin in question, but we'd need to figure out a decent list.....

**Comment by s520** [comment]
I certainly understand that there is a danger and that the logic should be implemented in the main program.
However, there are limited people who can change the code of the main program like ours.
I think that plug-in should give some flexibility.
