### ISSUE TITLE
Suggestion/musing about AssemblyInfo.tt

### ISSUE THREAD

**Issue by mgavioli** [leezer3/OpenBVE#32]
This is not a bug report, but rather the start of a discussion about how to remove a little dev complication (if there is a better place for this kind of things, please tell me!).

A sort of a little conundrum here:
1)  `AssemblyInfo.tt` relies on an existing `AssemblyInfo.cs` for the major and minor version numbers (and for the build number, but more about this later)
2)  => `AssemblyInfo.cs` must be under version control (to make major and minor version numbers known)
3)  It generates a new `AssemblyInfo.cs` each time it is run
4)  => `AssemblyInfo.cs` is better left out of version control, or merge conflicts may arise.

(Note: I do have a merge conflict on **each** update I fetch from upstream, unless I remember to revert any local automatic changes to `AssemblyInfo.cs` **before** merging it; so the case is not purely hypothetical).

Is there a strong reason not to store the major and minor version numbers directly in `AssemblyInfo.tt` and get rid of its dependency upon `AssemblyInfo.cs`? This would allow to remove the latter from version control and avoid any merge conflict.

Agreed, this would not be a standard place to store source data for version numbers and would puzzle the 'casual developer' (like myself!). But, admittedly, changing the version number is not an operation for the 'casual developer', it is usually the domain of a project manager.

The only remaining point is the build number and the test `AssemblyIfo.tt` performs on the previous one to make sure it is not greater. It looks a wise thing to do, but is it **really** necessary? How probable is that the system clock of develoepr A and/or the system clock of developer B are so wildly off time that developer B fetches a commit from developer A to discover that it has been made _tomorrow_?

**Comment by leezer3** [comment]
In an ideal world, I'd not commit any of the scripting in assemblyinfo.tt
at all, so that the version number is only updated on 'my' box...
I did investigate trying to exclude the pre-build script change, but the
sln file changes when extra source files are added.

I wonder if I could change the .tt file to blank/ untracked?

Need to do some major thinking; This is what happens with multiple devs.....

**Comment by mgavioli** [comment]
Just in case it can be of any help, for another open source I contribute to, a very similar problem as been addressed with this git post-checkout hook:

    #!/bin/sh
    # only do this for branch-level checkouts
    case $3 in
    1)    git update-index --assume-unchanged mscore/revision.h
          git rev-parse --short HEAD >mscore/revision.h
          ;;
    esac

In the specific case, `revision.h` (the name is largely historical and the file is not a C header at all) is not under version control; rather it is stored in the executable as a resource and read at run time to internally set (and openly display) the version, but other solutions are possible, I believe. The main point of the 'trick' is to use git hooks.

**Comment by mgavioli** [comment]
While searching about this, I found that it seems possible to put:

    [assembly: AssemblyVersion("1.4.*")]

and removing the `[assembly: AssemblyFileVersion(...)]` line to have the build and revision numbers automatically generated from date/time. Some peoples seem to have had problems with this, but it is perhaps worth trying?

**Comment by leezer3** [comment]
Right, I think this may be what we're after:
https://github.com/leezer3/OpenBVE/commit/d342b7754fe6313b77a16163b519c7577d71f7f5

Changes are as follows:
Build number increments once a day, no matter what. That's not quite perfect, but I think we can live with that.
Revision number works exactly the same way (Minutes since midnight)
I've added the username of the compiling user onto the end- This is mostly because of the auto-generated builds.

I'm still not quite satisfied with this, but think it'll probably do for the moment- Perhaps it wants the Git commit hash rather than the username, but IIRC that falls over when making a build from un-commited changes?

**Comment by JakubVanek** [comment]
Travis build failed:
"CSC: error CS2001: Source file `Properties/AssemblyInfo.cs' could not be found"
"/home/travis/build/leezer3/OpenBVE/openBVE/OpenBve/OpenBve.csproj:  warning : TextTransform missing and /p:TextTransformMono=[path] not specified! Ignoring TextTransform."

**Comment by leezer3** [comment]
Yeah, my fault- Needed to set Travis to install Monodevelop so that TextTransform.exe was available.
(Why it's in the monodevelop package and not mono-devel I don't know......)

I've also discovered that this dependancy on the monodevelop means that Travis doesn't build on anything other than mono-latest (Unresolved dependancy issues), which I probably ought to sort in the .travis.yml file, although the compiled build should still work on earlier versions.....

**Comment by JakubVanek** [comment]
Just downloading and extracting a prebuilt version from previously known URL would probably suffice.
This is Ubuntu's build: [texttransform.zip](https://github.com/leezer3/OpenBVE/files/165230/texttransform.zip)

**Comment by mgavioli** [comment]
As far as I can see, the issue is solved: no longer any `AssemblyInfo.cs` conflict and build works fine!
