### ISSUE TITLE
The game can not start

### ISSUE THREAD

**Issue by s520** [leezer3/OpenBVE#321]
### Description

Windows Form ends and game screen does not start despite selecting the route and selecting the train, ~although the start button is not pushed~.

### Reproduction

Please watch the video below. (The green part is to hide the real name.)
https://twitter.com/ytukuri_rs2/status/1100413999005327362

## Route

It does not depend.

## Train

It does not depend.

## Logs

[openBVE Bug Report27_02_2019.zip](https://github.com/leezer3/OpenBVE/files/2910213/openBVE.Bug.Report27_02_2019.zip)

### Related information 

- Windows 10 x64 RAM: 16GB
- This is a phenomenon occurring on my friend's computer. I will post on his behalf.

**Comment by leezer3** [comment]
That's interesting- The log is totally blank.

It's not going to be directly route, train or PC related, as we pre-process the route just fine. (Track diagram etc is visible)

First suspect would be graphics card drivers failing to create an openGL context & hence the main game window. 

What graphics card?

**Comment by s520** [comment]
He pressed the start button. I'm sorry.
I will ask him about the type of graphic board.
Is there anything else I would like to ask him?

**Comment by leezer3** [comment]
No trouble.

Looking into the logging code, the logging to file only really starts after the main game window is spun up. As we're not even getting this, it really looks like the window is failing to launch at all.
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/System/Loading.cs#L172

However, if the gamewindow fails to load, we ought to spit out one of the error messages found in this function (Although they are popups as opposed to in the log):
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/Graphics/Screen.cs#L31

---

Other thoughts / observations:

Something else that looks a little odd is the train picture.
Is that supposed to look like that, or is the image corrupted?

I've also seen some odd things caused by antivirus blocking stuff over the years. Might want to check that, but the main program launches.....
Can't explain this one at the minute.

---

I've added log events for the window creation and successful initialisation, which may shed a little more light on this, but unless we can figure out where it's failing I'm not sure how much we can do.

**Comment by s520** [comment]
He is using RX550 2GB.
According to him, this phenomenon happened suddenly this day.
I will tell him to try the latest build.

What is "train picture"?
![1](https://user-images.githubusercontent.com/29241703/53496000-72884b00-3ae4-11e9-8ad3-727d442f7a6b.png)
Or
![2](https://user-images.githubusercontent.com/29241703/53496020-7caa4980-3ae4-11e9-8f0a-0b7fe5ded3bc.png)

First and second are normal.

**Comment by leezer3** [comment]
I meant the one ringed in red in your second screenshot.

Happening suddenly sounds nastily like Windows deciding to automatically update the graphics card drivers to me.

**Comment by s520** [comment]
OK. Let's ask him.

**Comment by s520** [comment]
He seems to have failed to initialize the game window.
[openBVE Bug Report27_02_2019 (1).zip](https://github.com/leezer3/OpenBVE/files/2910711/openBVE.Bug.Report27_02_2019.1.zip)

He said he did not update the graphics card driver. (Windows Update)

**Comment by s520** [comment]
Other programs using OpenGL also did not work.
Apparently it seems to be a problem with Windows 10.
He said that it worked properly in Ubuntu.
