### ISSUE TITLE
A lot of FreeOBJ cannot set to the world.

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#328]
Now we are working of BVE5 converter.
When we are converting the route of BVE5, we need to use FreeOBJ.
The BVE5's route image is not use RailX.
Mainly using the command of 'Repeater'.
We imagines and discussed how to convert.
First, it is difficult to use OpenBVE's RailX.
Because, BVE5 can free to set the name to valiable.
So, for example, we cannot to find what is the Rail object of Rail0 automatically.
Finally, we decision to use FreeObj.
When we attempt to use FreeObj, we faces the some troubles.

1. the sample file of this, what is put a lot of FreeObj.
This is uses 20 Rails and 100,000 FreeObjs.
When we are attempt to convert a BVE5's data, that use about 100,000 FreeObj.
So, this sample is also uses 100,000 FreeObj.

When OpenBVE read this sample, OpenBVE is a lot of memory allocates, but very slowly.
Can the OpenBVE allocate the a lot of memory freely,  more fast, and compressing ?

2.We are now also to working about the BVE5 perser.
This perser is read directly from BVE5's route without converter.
This problem is also happens when the BVE5 perser running. 

3.Such as you seen the sample csv route, this problem also happens at the OpenBVE's csv route.

We want to solve this problem.
Please consider about this.

How to run the sample route.
1.Please download Object file of my Tohogu-shinkansen from this link. 
https://onedrive.live.com/redir?resid=2E630AFCBBE39699%21159

2.Extract Railway folder
3.Copy to Route folder downloaded sample route.
4.run this sample.

[freeobj100000.zip](https://github.com/leezer3/OpenBVE/files/3001664/freeobj100000.zip)

**Comment by leezer3** [comment]
You've just hit one of the fundamental limitations of the current openBVE engine.

At present, it's a largely single-threaded affair, and requires the whole world to be created in-memory prior to the start of the game.

If you look into the current CSV route parser, when it post-processes the route, for each object in a block, it calls the ObjectManager.CreateObject method ( https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/Game/ObjectManager/ObjectManager.cs#L42 )
This generates the transformed world model, and is essentially the slowest part of what's happening.

My initial thoughts for a potential gain on this issue would be to create a workload pool with threaded workers, so that object creation is passed to this.
This might see a **N - 1** times speedup, whereby **N** is the number of cores / threads available on the user's system.

---

This doesn't really address the whole issue though; The more 'common' approach to world generation is to use a tiled approach, so that the world is generated in small batches.
There's a prototype version of openBVE2 by Michelle kicking around here which does that, but is missing all of the train code etc:
https://github.com/sladen/openbve2/tree/master/OpenBve

**Comment by s520** [comment]
I consider memory growth to be a problem rather than speed.
Let's take a look at the prototype code.

**Comment by leezer3** [comment]
They're somewhat intertwined here.

The prototyping code clones the entire object before applying the transofmations, which is what's causing the memory growth you're seeing.

**Comment by s520** [comment]
Well, does that mean that even the prototype code can not solve the memory problem?

**Comment by leezer3** [comment]
Not easily.
This is the function in question:
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/Game/ObjectManager/ObjectManager.StaticObject.cs#L339

We could apply a little mild parallelization to the vertex / face cloning, but the gains here are pretty minimal unless the objects are using multiple thousands of vertices; For your typical CSV / B3D object with under 100 vertices and a few faces, the cost of the parallelization here is about on par with what it saves.

**Comment by s520** [comment]
Hmmm...
Can we reduce memory usage if we transform objects dynamically, in combination with tiling methods?

**Comment by leezer3** [comment]
That would absolutely work, but I don't know how much effort it'd need.
Off the top of my head, it'd definitely break stuff in the lighting model (this expects each object to be unique) and possibly other places too.

Doing that, you'd also have to implement some sort of background thread to load the new tiles; Updating the animated objects in the world is already bad enough at blocking the main thread without generating tiles as we go :)

**Comment by ginga81** [comment]
Each BVE2/4's old csv objects has may be 100 vertexes or lower.
But recently, especially to load BVE5's directx object that  is very precision, there is need to load a lot of vertex per object.
Unfortunately, my sample data cannot to ready to create precision object.
So this sample is not  a bit praccision.
The BVE5's  DirectX object, what is created by 3d modeling soft such as metasequoia and Blender.
When we are loading some BVE5 route, we need a lot of memory.
So, we need frexible memory allocating system.

**Comment by s520** [comment]
As ginga81 says, we need to deal with objects with a large number of vertices.
Do you have other good ideas?

**Comment by ginga81** [comment]
This issue is fixed by new renderer.
So, I close this issue.
