### ISSUE TITLE
[Request] Couple section with model

### ISSUE THREAD

**Issue by ManuelMejias** [leezer3/OpenBVE#381]
Articulated train part it's a problem to model with two pieces, a coupler model could be a solution to this.

Some simulators such as Train Simulator saga use a unique model piece to joint trains avoiding that "empty" result on a curve transition.

**Comment by leezer3** [comment]
That sounds like a very logical addition.

I'll try and look into it at some stage soon-ish.

### Brainstorming thoughts:

- Bogie connects to two cars.
- We need the position, direction, up & side vectors for the bogie in order to move the animated object appropriately.
- For a car, this is calculated as follows:
```C#
// calculate positions and directions for section element update
Vector3 d = new Vector3(FrontAxle.Follower.WorldPosition - RearAxle.Follower.WorldPosition);
Vector3 u, s;
double t = d.NormSquared();
if (t != 0.0)
{
	t = 1.0 / Math.Sqrt(t);
	d *= t;
	u = new Vector3(Up);
	s.X = d.Z * u.Y - d.Y * u.Z;
	s.Y = d.X * u.Z - d.Z * u.X;
	s.Z = d.Y * u.X - d.X * u.Y;
}
else
{
	u = Vector3.Down;
	s = Vector3.Right;
}
Vector3 p = new Vector3(0.5 * (FrontAxle.Follower.WorldPosition + RearAxle.Follower.WorldPosition));
```
Assume therefore:
- Replace the front / rear axles with the appropriate car axles.
- Up vector can probably be averaged across both cars as opposed to from the car root?
- Show / hide as per bogies & car objects?

Issues:
- This would anchor on the car axle pivot point, not the end of the car ==> Is it worth calculating an offset point? Can get a directional vector from the two axle positions and use this. but effort.....
- Check how the coupler stretch / compress works. IIRC this is just a regulation of the distance between the car ends?
- Doesn't take account of coupler stretch / compress properly.
- No scale object function (see above, probably generally useful!)

**Comment by leezer3** [comment]
Implemented- You can now add a **Object** to a coupler declaration.

Will try and get around to thinking about growing / shrinking objects some stage soon.
