### ISSUE TITLE
Joystick controls cannot be assigned

### ISSUE THREAD

**Issue by jsiren** [leezer3/OpenBVE#4]
When a single joystick is plugged in, it does appear in the controls configuration screen as number 1, but doesn't react to axis motions or button presses; therefore controls cannot be assigned to it. However, when controls.cfg is manually edited to include lines for joystick n, they appear as assignments for joystick number n+1.

See also #3

**Comment by leezer3** [comment]
The most recent build improves joystick handling on Linux considerably, and may well help matters.
See what happens & report back 

Some technical info:
When OpenTK uses the SDL2 backend, the joystick does not move in the menu.
This is now not the default option, however an error message has been added stating to use the in-game menu.

This can be changed via changing the value of **preferNativeBackend** in the configuration file, but there is no UI option. 

The native (evdev) backend wasn't working properly at all, due to a combination of factors- openBVE created it's internal joystick list once on load, whilst OpenTK doesn't register a joystick as existing on Linux / Mac until it detects a state change.
