### ISSUE TITLE
Compiled builds listing

### ISSUE THREAD

**Issue by JonnyTech** [leezer3/OpenBVE#45]
>Daily auto-generated builds available from here as of now-
http://vps.bvecornwall.co.uk/OpenBVE/Builds/

The builds are listed oldest first. Can they appear newest first please?

Maybe also have a link to the most recent or stable build somewhere too.

**Comment by leezer3** [comment]
Sorting reversed.

Most stable is a little more problematic, simply because it requires manual work, and for that matter something we consider to be stable!

These builds are getting a lot more stable, but they're not currently what I'd consider perfect.
In general terms, the most recent build *should* be the most stable. 

Will think about listing the most recent manually uploaded  build in the header or something and get back to you.
In general though, I'm posting builds I consider to be relatively stable in these two threads:
http://bveworldwide.unlimitedboard.com/t1229p300-new-openbve-build-testers-please#13932
http://forums.uktrainsim.com/viewtopic.php?f=66&t=143351&start=30
