### ISSUE TITLE
Crash on specific combination

### ISSUE THREAD

**Issue by JonnyTech** [leezer3/OpenBVE#46]
Tried a line with the latest build:

> mono OpenBve.exe
> Stacktrace:
> Native stacktrace:
>     mono() [0x4b73d8]
>     mono() [0x50f13b]
>     mono() [0x423d22]
>     /lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f4488cc8340]
>     /usr/lib/nvidia-340-updates/libGL.so.1(+0xd7c09) [0x7f4466b7fc09]
> Debug info from gdb:
> Could not attach to process.  If your uid matches the uid of the target
> process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
> again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
> ptrace: Operation not permitted.
> No threads.
>  =================================================================
> Got a SIGSEGV while executing native code. This usually indicates
> a fatal error in the mono runtime or one of the native libraries 
> used by your application.
>  =================================================================
> Aborted

Combination of the following:
Route: OpenBVE Northern Line. Edgware - Morden via Bank 1998
Train: 1992TS

Trying that route with another train, or that train with another route, both work fine.

Same problem in both fullscreen and windowed mode. After pressing start, the splash screen shows and the progress bar fills. Once full bar, the application quits.

**Comment by JonnyTech** [comment]
Yes, I concur - damn Nvidia!
nvidia-340-updates version 340.96

**Comment by leezer3** [comment]
Whilst I don't think this will help, please try the most recent build with 'Unload Unused Textures' activated under options.

There was(is??) a bug on OS-X where openGL would crash with an *OutOfMemoryException* due to too many textures being loaded.
I added an option to try and get round this, but it caused textures glitches....

Today's build revises that option considerably, and **if** this is related to something similar, it may help.
No guarantees though.

Running openBVE via GDB may produce some interesting output too if it catches the driver crash.

**Comment by JakubVanek** [comment]
> Running openBVE via GDB may produce some interesting output too if it catches the driver crash.

```sh
sudo apt-get install mono-dbg mono-runtime-dbg
gdb -ex run --args mono /path/to/openbve/exe
# then do something to trigger crash, gdb should confirm that
# enter this
bt full
```

**Comment by JonnyTech** [comment]
Thanks - I shall be at that machine this weekend to test and report back
