### ISSUE TITLE
Translate command processing all commands instead of only one

### ISSUE THREAD

**Issue by Railfan007** [leezer3/OpenBVE#460]
### Description
When Cylinder and Cube commands are under the same CreateMeshBuilder command, Translate works for all Cylinder/Cube commands, and not each command individually. I also isolated the commands into a separate file and tried again, same issue. The documentation page says it should not be happening with such commands here: https://openbve-project.net/documentation_hugo/en/objects/native/csv.html#translate

### Reproduction
https://media.discordapp.net/attachments/694077682333253664/699968428210913320/unknown.png

```
CreateMeshBuilder ;;1
Cylinder,8,0.05,0.08,0.06
Translate,-1.425,-0.135,0.12
Cube,0.1,0.02,0.1
;Translate,-1.425,-0.17,.12 ;remove/add the semicolon in front of Translate to produce issue
;SetColor,150,150,150
```

### Related information 
* Operating system = Win 10
* Method of control = Keyboard and Mouse

**Comment by leezer3** [comment]
This would appear to be as documented:
**moves all vertices that have been created so far**

In other words, each translate command moves upwards through the file, moving vertices as it goes until it encounters a MeshBuilder command.

---

### Let's demonstrate:

(I've colored the first cylinder red for ease)

First, let's start with no translation:
![nt](https://user-images.githubusercontent.com/7688245/79346932-e117aa80-7f2a-11ea-8cb1-f729f045abd9.png)

Both are in the same place, as expected.
I then move the cylinder as per your first translate command. In order to demonstrate that nothing else is moving. I've added a second cylinder in blue in the original position.
![nt1](https://user-images.githubusercontent.com/7688245/79347146-33f16200-7f2b-11ea-800f-75bbb7fe5dbb.png)

Finally, I uncomment the second translate command:
![nt3](https://user-images.githubusercontent.com/7688245/79347294-68651e00-7f2b-11ea-988e-45e7e4a17a61.png)

Our first cylinder is affected by both translate commands, and hence ends up at the following position:
-2.85, -0.305, 0.24

The cube is only affected by the second translate command (as it follows the first), and so ends up at the following position:
-1.425,-0.17,0.12

**Comment by Railfan007** [comment]
ohhhhh. I figured I missed understood something. Thanks again!
