### ISSUE TITLE
OpenBVE will crash if the route has more than 3414 section command

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#557]
### Description

On the latest build (Not nightly build, the latest one from github)/Windscreen build on bveworldwide, if a route has more than 341x (Around 3410-3420) .section command, it will crash without any log on the log.txt (System.StackOverflowException)

## Route
[section.zip](https://github.com/leezer3/OpenBVE/files/5559969/section.zip)

## Logs

[log.txt](https://github.com/leezer3/OpenBVE/files/5559986/log.txt)
No crash log generated

### Related information 

* OS: Windows 7
* Method of control Keyboard

**Comment by leezer3** [comment]
Now that's odd.

I don't think I've touched sections in there; It's probably an out of memory generally.

That many sections is going to be asking for trouble.
Will take a look later.

**Comment by leezer3** [comment]
Fixed in the latest nightly. (Not in the windscreen branch, I'm going to release a newer version at some stage this week, then merge that one into the main)

I wouldn't reccomend using this may sections (or aspects) without a very good reason though, as I'd strongly suspect this may well crash some train plugins (and possibly animations too)
