### ISSUE TITLE
[Request] Add a variable to tell if the current Train is being used on setInterval in .animated

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#576]
setInterval command spawns an A.I. Train with the player's train model. But I don't think there's an animated variable to tell whether the current animated is being used on the preceding A.I. train
(Or is it even possible to implement it?)

My use case is randomize the car number and the LED route destination of the previous train with Light Rail Vehicle

I know TFO might be more suited on this part, but currently I don't think TFO is being recognized by the A.I. feature, they couldn't dynamically stop the train when a player train is in front, and there's no way to tell the distance from the TFO with the plugin (I have an custom crash animations)

Other than that, I couldn't think of a better approach anymore

Thanks for your consideration

**Comment by leezer3** [comment]
My initial thought would be that you're over-complicating things somewhat.

What I think you really want is simply the option to tell if any given train is the player train or not.
This has been added as the animated variable **PlayerTrain** - Returns 1 if the train is the player train, 0 otherwise.

**Comment by Kenny-Hui** [comment]
Ah I see, that's exactly what I wanted
Briefly searched the documentation before I make the issues, somehow I still misses it

**Comment by Kenny-Hui** [comment]
Thanks, that's exactly what I wanted!

**Comment by Kenny-Hui** [comment]
Tested and works perfectly, resolved.

**Comment by BPI-919** [comment]
I have this file:
![kép](https://user-images.githubusercontent.com/66689434/139596027-7dc03b59-6e22-45eb-8438-9ac995a6b018.png)

It is a tram object ("static" object), that has connected to a tram-route (tram line 3) via Structure.freeObj command. Tram line 3 has used like a test route by me.

My problem is: Although I have specified that the wheels, which connected to the bogie of a tram-object (static object) should only rotate if it is assigned to our driveable vehicle, which is not the case in the present case, however here we find that the wheels will rotate, if I begin increase the driveable vehicle's speed. It's like, the value of the playerTrain variable in .animated files, has being set to 1, all the times, or the program could not recognise that this .animated file is not connected to the drivable vehicle / player's train. If the program could recognize this, and in this case give 0 to the value of the playerTrain variable, there would be no problem.
I don't know exactly why this bug is present, now.

Could you solve it, Chris, please?

Thanks, Andrew

**Comment by leezer3** [comment]
That's interesting- Must have overlooked that case.

Should be an easy fix.

**Comment by leezer3** [comment]
Sorted :)
