### ISSUE TITLE
Object reference not set to an instance of an object when selecting trains while parsing route in the menu.

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#628]
### Description

While parsing route, you can select the train at the same time.
After the new TrainManager updates. If you have just selected a route and select the train quickly, the route description will be "Object reference not set to an instance of an object" and you have to reselect the route to start the game.
![image](https://user-images.githubusercontent.com/28094366/117578089-3d91cd00-b11f-11eb-84ec-8e70bd43bd0d.png)

### Reproduction

While this generally works as described above, to have an more consistent reproduction, follow the steps below:
1. Launch OpenBVE
2. Swap between 2-3 routes quickly while parsing
3. Quickly select any train

### Related information 

* Operating system: Windows 10 20H2
* Method of control: Keyboard

**Comment by ginga81** [comment]
This trouble also happen at my environment.
to fix, re-select the another route, and select correct route.
This action is a bit bothersome.

Related information:
My PC's SPEC:

OS: Ubuntu18.04LTS(64bit)
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Graphic board:Radeon RX 590 Series (POLARIS10, DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0)

**Comment by s520** [comment]
This issue is caused by unloading and reloading the content loading plugins when user selects a train.
https://github.com/leezer3/OpenBVE/blob/d83d655ae5c0ce6afefd87863af851f84f98cf0a/source/OpenBVE/UserInterface/formMain.Start.cs#L1020-L1027
When unloading, the loading of routes running in another thread is cancelled.
If it is cancelled, an exception will be thrown because it will try to draw a schematic of the route based on incomplete data.
I'm working on solving this issue, but I still need some time.

**Comment by leezer3** [comment]
Good spot, thanks.

The initial 'fix' is likely to be not to call the unload function in the first place, and change it so that if the plugins are currently loaded it just returns true; I think the route / train plugins both are guarded so that only one instance works at a time.
The route preview thread also unloads the plugins once finished, which would want changing.

Longer-term, I suppose we would need something like a loading queue, although that might only be necessary for trains. (I can't see a need for loading different routefiles in paralell. Perhaps if we moved to a tile based system, but that would involve throwing out the entire current world)
