### ISSUE TITLE
Wrongly named .nuspec file for OpenTK GL Control fork?

### ISSUE THREAD

**Issue by danfe** [leezer3/OpenBVE#705]
It is named as `OpenTK.GLControl.nuspec`, but FreeBSD's Mono/NuGet framework won't handle it unless I create a symlink to this file named `OpenTK.GLControl-OpenBVE.nuspec`.  Is there some inconsistency between the metadata and actual filename?

**Comment by leezer3** [comment]
Dangerous question :)

It proved quite a PITA to get the fork working with dependancies correctly, and this is the first time I've tried it. (There are actually no changes in the GLControl package, but we needed to create a clone in order to stop it depending on the outdated OpenTK package)

Sounds like the metadata file needs renaming in the archive, but I'm marginally surprised it's worked on everything else....
Will try and look at it in the next few days.

**Comment by danfe** [comment]
Perhaps the problem is not with the package itself, but with this line from the `TrainEditor2/packages.config` file:
```xml
<package id="OpenTK.GLControl-OpenBVE" version="1.0.0" targetFramework="net472" />
```

**Comment by danfe** [comment]
Since custom OpenBVE's OpenTK.GLControl component version had been bumped to 1.0.1 this problem no longer occurs, closing.
