### ISSUE TITLE
Malware detected & unable to reinstall 1.5.0.4 after uninstalling

### ISSUE THREAD

**Issue by mperelmuter** [leezer3/OpenBVE#73]
I recently downloaded and installed openBVE 1.5.0.4 on Windows 8.1. At several places throughout the installation process my firewall (Comodo) was convinced that I was installing trojans and/or general malware. Here's one of the messages I got a screenie of.

http://imgur.com/8Sxwv8S

I eventually got it installed and used it to test a few routes and packages I made on my main BVE installation, but then decided to uninstall and reinstall the program. (I wanted to put it in a different directory and also get more screenshots of the malware detection.) I uninstalled it successfully, but when I try to reinstall it I get an error and the installation stops.

http://imgur.com/O63uXFo

This is unrelated to any of the above bugs, but I also had the issue of package content being installed into a location different from everything else, and IMHO it would be best to have a separate folder within the openBVE folder called "Downloaded packages" or something like that where all the automatically installed packages would be placed. They could also be chosen to play from a new tab alongside the one for choosing manually installed content, or even straight from the existing Package Management tab.

**Comment by leezer3** [comment]
As far as I'm aware, the installer is virus free. I've scanned personally
with MSE & Kapersly.
Virustotal:
https://www.virustotal.com/en/file/a317865b44d50498522b87f716901d413379c87310982c4455432d5b604a182b/analysis/1467556327/
Nothing much I can do about heuristic detections (which is what this looks
like)

I suspect the second error has probably got something to do with the first
(Have you got the heuristics on maximum for example)

Will try and setup a VM and reproduce this, but not a lot I can do in the
first instance....

I recently downloaded and installed openBVE 1.5.0.4 on Windows 8.1. At
several places throughout the installation process my firewall (Comodo) was
convinced that I was installing trojans and/or general malware. Here's one
of the messages I got a screenie of.

http://imgur.com/8Sxwv8S

I eventually got it installed and used it to test a few routes and packages
I made on my main BVE installation, but then decided to uninstall and
reinstall the program. (I wanted to put it in a different directory and
also get more screenshots of the malware detection.) I uninstalled it
successfully, but when I try to reinstall it I get an error and the
installation stops.

http://imgur.com/O63uXFo

This is unrelated to any of the above bugs, but I also had the issue of
package content being installed into a location different from everything
else, and IMHO it would be best to have a separate folder within the
openBVE folder called "Downloaded packages" or something like that where
all the automatically installed packages would be placed. They could also
be chosen to play from a new tab alongside the one for choosing manually
installed content, or even straight from the existing Package Management
tab.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/leezer3/OpenBVE/issues/73>, or mute the thread
<https://github.com/notifications/unsubscribe/AHVQNUIahIt4DB_ee6TnxDLKmRSiJFN_ks5qR8ShgaJpZM4JD4KX>
.

**Comment by leezer3** [comment]
Package management location:
This is semi-temporary at the minute.
Michelle hardcoded the current location in, and it was intended to be used with her version of managed content, but the route / train lists just open at the last folder shown, rather than any specific location.

At some stage, we'll need to figure out a 'correct' default location.
Storing files in the program directory is a big no-no on later versions of Windows and has been on Linux for a long time.
On a Mac, the program directory is hidden and not user accessible, so that's even worse :)

The Appdata folder is where the .Net specifications would like us to put this sort of stuff, but as you note, it's not entirely user findable by default.

**Comment by mperelmuter** [comment]
I suppose the best option would be to let the user choose a default location at installation, with an option to change it later? Even if you/other developers choose to stick to .NET's preferred Appdata location, there could still be a "jump to default location" button near the folder navigation window.

Regarding the earlier bug with inability to reinstall, it was due to an error on my part. What ended up working was selecting "run as administrator" while logged in as an admin. The firewall still insisted that I was installing trojans but as you said, those algorithms aren't as good as they should be.

**Comment by leezer3** [comment]
That's actually quite a good idea.

I think what it probably wants is a dialog that pops up on first start, allowing the user to configure the display language and installation directories.
Not going to happen just yet, but I've created a tracking milestone: https://github.com/leezer3/OpenBVE/issues/75
