### ISSUE TITLE
Motion Blur intensity depend on train speed? 

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#766]
If I turn the Motion Blur to "High" in Options and rotate/move the camera around, there will not be any motion blur when the train stopped.

However when the train is running (Probably after 10-20km/h) the Motion Blur will start to become more visible.

It also does not seems to apply to F3/F4 view, is this intentional?

(Tested on OpenBVE v1.7.3.0, though only writing this issue on mobile now)

**Comment by leezer3** [comment]
The speed effect is intentional. (At least by Michelle)

Not sure whether it should affect external views, but it at first thought without checking the code *probably* shouldn't. Basically, I'm assuming the internal views to represent a person, whereas external a cinematic camera (??)

Not sure either is a bug, but happy to hear other opinions.
