### ISSUE TITLE
[Question] which bve5 route parser branch that will merged with master ?

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#776]
Hello

I wanna know which bve5 route parser branch that will merged with master ? Is BVE5_S520 or BVE5_route ?

Anyway i succeed build BVE5_S520 branch in my pc but i got some bugs this what i found:
- object poping out when moving camera forward (it seems because object culling right in camera position, it easly noticeable if you move camera higher, facing down and move it forward).
- in some route sky got black if hiding the UI
- in some route most of the object missing and rails is pointing upward.
- in some route fog turn very black

**Comment by leezer3** [comment]
Neither is perfect / completely finished, which is why they're not in master at the minute. The only things that work well with both are simple things like the default Keisei route and similar.

IIRC BVE_route is considerably faster, but has less of the signalling etc. Implemented.

(Announcing even partial BVE5 support is likely to bite if its a mess)

It's on my list of stuff to

**Comment by adfriz** [comment]
Yup i know both branch is not completed.

Well if you say BVE_route is faster im gonna try build it soon and maybe compare it with BVE_S520 branch.

Yeah announcing incomplete feature is bad idea.

Anyway is there a plan to update those branch so it will same level as master ? Because both branch seems had more than 50 commit behind master, i think maybe updating those branch make it better.

**Comment by leezer3** [comment]
AFAIK there's nothing in the master branch that will affect either of these.

**Comment by adfriz** [comment]
Oh ok, because this question has been answered im gonna close this issue.
