### ISSUE TITLE
cannot finish building openbve.exe in VS community 2022 for windows

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#778]
### Description

when building openbve 1.8.3.1 the executable for main program raise an error exited with code 9009

### Reproduction
 - download source code for 1.8.3.1 in github release page
 - open the solution in vs community 2022
 - restore the nuget packages to download required dependency
 - change the build to release mode
 - build the solution
 - you gonna get 2 error for the openbve exe
## Route

no route

## Train

no train

## Logs

this log error message i got
![error](https://user-images.githubusercontent.com/76892624/162709473-1c1f62db-3e1b-4823-96da-cc79880eeb8b.jpg)

### Related information 

* Operating system: windows 10 64 bit
* Method of control: Keyboard and mouse

**Comment by adfriz** [comment]
It seems AssemblyInfo.tt need AssemblyInfo.cs but that file is not exist.

I already tried several method below but still give an error:
 1. Rebuild the solution wiht debug or release mode
 2. Clean solution and rebuild it again

Note: i use latest master and 1.8.3.1 source code from github release page, but both still give this error.

**Comment by ginga81** [comment]
Mr. leeser3 is very kind , so he maybe answer for you.
But, if a build on Linux like me fails, there may be an OS-specific case, so you may raise the issue here, but your environment is Windows.
And almost everyone who builds a program in an integrated development environment has programming knowledge.
But if you look at your other posts, you probably don't have any programming knowledge.
Also, if you answer every time with Windows that many people are building individually, development will be stagnant each time.
And if he answer it carelessly, the beginners of the programers can easily ask a question every time the build fails in the future.
From these things, I don't think you should hear about the problem of individual build failure in the project portal.
If you still want to hear it individually, I think it's a problem you should ask at BVE Worldwide.
https://bveworldwide.forumotion.com/

**Comment by Kenny-Hui** [comment]
I am assuming it's because the folder has space (**openbve source**)
In windows, you usually need to add a quote, if I remember correctly it will be smth like:
`"D:\openbve source\OpenBVE-1.8.3.1\bin_release\DevTools\LBAHeader.exe" "D:\openbve source\OpenBVE-1.8.3.1\bin_release\OpenBve.exe"` but the post build command don't do so I think<?>

The easiest method is probably to rename the `openbve source` folder to `openbve_source`, try again and see if it works

**Comment by adfriz** [comment]
@ginga81 firstly thanks for your answer, yup i didnt have programming knowledge that why i heavily rely on this guide for building https://github.com/leezer3/OpenBVE/blob/master/Building.md and your anwers on #773 .

i also understand asking for answer fo every individual build if the build fail that a bit annoying and can slow down the development for the main build, but in this case im not changing anything, i just simply download the source code, open it in visual studio, restore nuget package, build it with release mode. But it give an error, i also dont understand why the source code for 1.8.3.1 give an error when i build it, i expect if the stable release is available so the source code for that shouldn't have any error because if there an error the like i got, the stable release is impossible to get released.

I think asking for answer for this error is right in here not at bve world wide forum because in my case i didnt change anything in term of code.

@Kenny-Hui hmm i dont know that, maybe that works, i will try it soon

**Comment by leezer3** [comment]
That I think should fix it.

**Comment by adfriz** [comment]
thanks everyone it works :)

i tested the 1.8.3.1 source code with using one or both method and the error is gone, i didnt expect the solution that simple just to delete or change the spacing in `openbve source` name folder.
