### ISSUE TITLE
[Question] Input Device Plugin's Elapse Data

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#796]
### Description

I am trying to create a Input Device Plugin which requires the player's train data.
For routes with only the player's train, this worked as intended.
But after adding Route.RunInterval, `data.Vehicle` will only return the data of the First Train rather than the Player's train.

It seems that the ElapseData of an ATS Plugin will just get passed to an abstract method, so only that specific plugin can receive the vehicle data. (Intended behavior)

https://github.com/leezer3/OpenBVE/blob/aadbd8a57d8ac9e2a12064e2b3dc80e19063908c/source/TrainManager/SafetySystems/Plugin/Plugin.cs#L160

But the Input Device Plugin's SetElapseData will get called whenever `UpdatePlugin()` is called (Across all train plugin)
https://github.com/leezer3/OpenBVE/blob/aadbd8a57d8ac9e2a12064e2b3dc80e19063908c/source/TrainManager/SafetySystems/Plugin/Plugin.cs#L168

This also includes AI Train as they also have a default plugin loaded.
This would result in erratic data when combined with AI Trains, as the SetElapseData method is called across different trains all with different data.

### Reproduction
- Add some preceding trains on a route
- Get vehicle data from SetElapseData

### Related information 

* Operating system: Windows 10 21H2
* Method of control: Keyboard
* OpenBVE Version: 1.8.3.2

**Comment by leezer3** [comment]
That looks like a bug. Certainly, *most* train plugins are only really concerned with the player train, and I can't see a good reason off the top of my head why an input device  plugin should be concerned with PreTrains

Having said that, the InputDevicePlugin interface cane from S520 / MarcRiera.

Will try and investigate later in the week.

**Comment by MarcRiera** [comment]
I've taken a look at this and the issue is indeed that data gets passed to the input device plugin for any train, not just the player train. I had actually noticed strange behaviour with one of my controllers in some cases but I wasn't able to recreate back then. Now I see it's happening on routes with pretrains.

Taking a look at the core InputDevicePlugin code, partly written by myself, I see that the following functions send data from any train:

- `SetVehicleSpecs`
- `DoorChange`
- `SetSignal`
- `SetBeacon`
- `SetElapseData`

I'll fix this, run tests and report back. Thanks!
