### ISSUE TITLE
S520's Detail Manager can't load from 1.8.4.1

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#813]
### Description

When we using the Detail manager created by S520 , ATS plugin don't loading.
To 1.8.4.0, it works fine. 

### Reproduction

Route is maybe any.
But, Train fits the route, please use my Shinkansen.
http://midnightexpginga81.web.fc2.com/touhoku_shinkansen/route_data/Touhogu-Shinkansen-Routedata-v0.09.zip
http://midnightexpginga81.web.fc2.com/touhoku_shinkansen/route_data/Touhogu-Shinkansen-Routedata-fromSendai_v0.06.01.zip

Objects and sounds
https://drive.google.com/uc?export=download&id=1lc4B8zgq9PhQM8BCEqAGNaU-u47mZET3

## Route

Route is maybe any.
But, Train fits the route, please use my Shinkansen.
http://midnightexpginga81.web.fc2.com/touhoku_shinkansen/route_data/Touhogu-Shinkansen-Routedata-v0.09.zip
http://midnightexpginga81.web.fc2.com/touhoku_shinkansen/route_data/Touhogu-Shinkansen-Routedata-fromSendai_v0.06.01.zip

Objects and sounds
https://drive.google.com/uc?export=download&id=1lc4B8zgq9PhQM8BCEqAGNaU-u47mZET3

## Train

F81_tec200's Series-E2-1000:
https://youtu.be/mSYEMUcHomE

additionally outer-view with Detail Manager
https://drive.google.com/uc?export=download&id=1GPZLjJTBiouuQQWO_Ae6KWKiA7AmmhZJ

## Logs

22:14:39  Loading train plugin: /home/user/デスクトップ/無題のフォルダ/Train/Tec_E2_1000_igbt-200color/ats/DetailManager.dll
22:14:39  The train plugin DetailManager.dll failed to load for the following reason: Method not found: void OpenBveApi.Runtime.LoadProperties..ctor(string,string,OpenBveApi.Runtime.PlaySoundDelegate,OpenBveApi.Runtime.PlayCarSoundDelegate,OpenBveApi.Runtime.AddInterfaceMessageDelegate,OpenBveApi.Runtime.AddScoreDelegate)

### Related information 

My PC's spec:
OS:Ubuntu 20.04 LTS 64bit
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Memory:31.3GB
Graphic:AMD Radeon RX 590 Series (POLARIS10, DRM 3.40.0, 5.11.0-40-generic, LLVM 12.0.0)

**Comment by leezer3** [comment]
Fixed.

He's doing something slightly unexpected by re-creating the initialiser, but the constructor was public :/
This is a quickly improved version of DetailManager to fix another couple of issues:
[DetailManager.zip](https://github.com/leezer3/OpenBVE/files/9485181/DetailManager.zip)

### Changes:
* Compiled using AnyCPU so it works on 64-bit variants of OpenBVE.
* If a child plugin fails gracefully the failure reason is passed back to the main sim.
* If a child plugin crashes on load, this is passed back to the main sim rather than taking things down.

**Comment by ginga81** [comment]
The DetailManager attached to the outer view solved the problem that it became anycpu in 1.8.0.0 and could not be started.
This was that while he was getting sicker, he had it urgently compiled and distributed on Slack for us.
Thank you for doing other fixes this time.
It seems that there is no prospect of improvement in the disease yet, but I will use this version for distribution from now on.
Thank you very much.
Also, the DetailManager included in the outer-view distribution now works also normally.
So, this issue is closed.

**Comment by leezer3** [comment]
https://github.com/leezer3/DetailManager_For_OpenBVE
[DetailManager 1.0.0.1.zip](https://github.com/leezer3/OpenBVE/files/9491552/DetailManager.1.0.0.1.zip)

### Couple more small patches:
- If two plugins which modify the brake notch are used, the most restrictive brake notch is returned. (the original version returns the brake notch value set by the last plugin)
- Use API path resolution function, as otherwise under Linux plugin file names were case sensitive.
- Unload and log if a child plugin crashes during an elapse call.
