### ISSUE TITLE
Replenishment station

### ISSUE THREAD

**Issue by JunmoreHeavyBox** [leezer3/OpenBVE#829]
There needs to be a place to replenish the train with abstract consumables.
Replenish the sander.
Check out the XML station by the way.

 - Possible future
Replenish water and abstract fuel for steam locomotive.
Replenish consumables for supply trailers.
Charging of battery locomotives without pantographs.

**Comment by leezer3** [comment]
Not sure this is a station property, really wants an entirely new command.
(otherwise they end up in timetables etc. etc.)

Haven't added anything for sanders replenishment, as this wouldn't generally be something done en-route.
As a secondary thought, we need the ability to specify in the routefile the starting sand etc. levels....

**Comment by ginga81** [comment]
BVEC_ATS specified a water supply and coal supply area with a beacon, and stopped and replenished there,isn't  it?
