### ISSUE TITLE
[Question] how to shift texture and stop on certain value ?

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#846]
As the title said, how to stop shifting until certain value?

I want to make curtain open and close with texture shift function, the shifting operation is triggered by key press through plugin like bvec, like my example in https://github.com/leezer3/OpenBVE/issues/832#issuecomment-1313100897 although that using statefunction.

In word is : when pluginstates[10] is 0 dont start shifting(stay as is) but when pluginstates[10] is 1 start shifting downwards every 1 pixel every frames and if already shifted 256px stop shifting and stop the function.

Here how i write it:
In .animated file

`[Object]`
`States = curtain.b3d`
`TextureShiftYDirection = 0, 1`
`TextureShiftYFunction = ???`

Here the texture example:
![AA](https://user-images.githubusercontent.com/76892624/209436178-99dd2300-81f4-457b-8d83-8b9525d5fb86.png) 512x512 px

Also i dont know is better using png with alpha channel that easier or using jpg and specify the RBG value that marked as alpha in b3d file later.

**Comment by Kenny-Hui** [comment]
Breaking it down step by step:

## Step 1 - Scrolling Infinitely
**Full Function:** `value+0.003`  

"value" means the last evaluated result, and 0.003 means it will scroll the image by 0.003 (0.3%).
This function will result in the texture scrolling non-stop. (Shifting 0.3% of the image every frame)

So the `value` variable would goes as follows:

Game Start: `0 (Starting value)`  
Frame 1: `0 + 0.003 = 0.003`  
Frame 2: `0.003 + 0.003 = 0.006`  
Frame 3: `0.006 + 0.003 = 0.009`

## Step 2 - Pluginstate Toggle
**Full Function:** `if[pluginstate[10] == 1, value+0.003, 0]`  

If statement syntax: `if[condition, <value if true>, <value if false>]`

So it would goes as follows:
If pluginstate[10] == 1:
  Scroll the texture as mentioned above (value + 0.003)
Otherwise:
  Reset the texture shift to 0 (Full curtain)

## Step 3 - Holding the curtain
**Full Function:** `if[pluginstate[10] == 1, value+0.003, value]`  

The `<value if false>` has been changed from `0` -> `value`
This means if you deactivate pluginstate[10], it will still stop at the previous value and won't jump back.

## Step 4 - Stop before curtain is looped again
**Full Function:** `if[pluginstate[10] == 1, min[0.5, value+0.003], value]`  
min function syntax: `min[value1, value2]` (Returns the lowest value)

This means if `value+0.003` goes over 0.5 (Which is 50% of the image, aka 256px in here), it will stay at 50%/256px (Stopping it).

Now you should have a working downward curtain by toggling pluginstate[10].

## Step 5 - Raise the curtain up again
It's the same step as above, but using another pluginstate.
Also, you should instead use `value - 0.003` to shift the texture up  
You also want to clamp the value at 0 rather than 0.5 (So it won't go negative), so use:
`max[0, value-0.003]`. (`max` will choose the larger value, so it won't go below 0 if value-0.003 is below 0)

And now you should have a fully working curtain

## Step 6 (Optional - Frame-rate independent)
This step is not needed, but your player may not play at the same frame-rate as you.
If they have a very low fps (Say like, 10-15), their curtain will move slower as it is still moving the same amount (0.003) every frame.

To solve that, we have the `delta` value, which returns the time it took from the last frame to this frame.  
This means the lower the fps, the more time it takes for each frame, the larger the `delta` value is, and using that we can "compensate" the speed on lower fps:  
`0.003` -> `(0.003 * delta)`

And of course it only calculates the time between each frame, which is very small, so we need to raise the 0.003 value:  
`(0.003 * delta)` -> `(0.1 * delta)`

**Final Result of a downward curtain:**  
`TextureShiftYFunction = if[pluginstate[10] == 1, min[0.5, value + (0.1 * delta)], value]`

**Comment by adfriz** [comment]
thank you very much @Kenny-Hui it works but i change the final result to

`TextureShiftYFunction = if[pluginstate[10] == 1, min[0.5, value + (0.1 * delta)], max[0, value - (0.2 * delta)]]`
so when pluginstate number 10 is 0 it will going upward and stop.

here the video


https://user-images.githubusercontent.com/76892624/209630320-2cf13575-a87f-4eca-98b4-da1b93b9b99e.mp4
