### ISSUE TITLE
No an issue ,New build Request another platform

### ISSUE THREAD

**Issue by Saikatsaha1996** [leezer3/OpenBVE#892]
```
Os Android
Architecture aarch64(arm64)
Api - 30
```

## Request 

Can it possible to build apk for android? So it would be great.. now android device ram & processor & GPU is improving.. can it possible to build for android?

Thank you
Regards
Saikat Saha

**Comment by v1993** [comment]
I imagine it would be pretty hard, to say the least...

* Xamarin framework with brand new menu, windowing, input, etc. code in place of OpenTK
* In-game controls would be pretty challenging to adapt (not impossible, but some brainstorming needed)
* OpenGLES and/or Vulkan renderer since desktop OpenGL is unavailable there
* Filesystem stuff in particular would be tricky (android has pretty slow arbitrary file access times from what I know, likely necessitating installation of packages into app's directory to work)
* Possible need for new audio backend, but it's probably one of the easier parts...

While likely doable, it would be quite an effort, probably requiring some refactoring to decouple from currently usef libraries as well.

**Comment by Saikatsaha1996** [comment]
> I imagine it would be pretty hard, to say the least...
> 
> * Xamarin framework with brand new menu, windowing, input, etc. code in place of OpenTK
> * In-game controls would be pretty challenging to adapt (not impossible, but some brainstorming needed)
> * OpenGLES and/or Vulkan renderer since desktop OpenGL is unavailable there
> * Filesystem stuff in particular would be tricky (android has pretty slow arbitrary file access times from what I know, likely necessitating installation of packages into app's directory to work)
> * Possible need for new audio backend, but it's probably one of the easier parts...
> 
> While likely doable, it would be quite an effort, probably requiring some refactoring to decouple from currently usef libraries as well.



Actually for new generation GPU for Adreno 600 & Mali Valhall generation is really very good.. Openrail old version & msts working fine with wine.. i believe if we get android version application with `OpenBVE` we can get great performance with it..

Is it true we don't have have Desktop OpenGL inbuilt.. but we have custom mesa freedreno turnip & panfrost Mali GPU driver..

Like we can use custom GPU driver if we have custom GPU driver option like skyline emulator, PSP emulator or Vita3k emulator.. so we can use custom made mesa GPU driver with desktop OpenGL & vulkan.. because all emulator have options for custom GPU driver and useing mesa driver..

And now android filesystem also improved because now android useing UFS 2.0 3.1 ufs storage..

Playing Openrail with wine 20 fps mesa turnip GPU driver..

![Screenshot_2022-06-27-17-14-56-968_com ludashi benchmark](https://user-images.githubusercontent.com/72664192/235384080-7aac23eb-7e9b-4178-a01c-586c46972243.jpg)

**Comment by leezer3** [comment]
Well, OpenTK supports Android natively. (Xamarin.Android is a fork of an early OpenTK version fwiw)

The current GL3.2 implementation is pretty simple too, so ES shouldn't be too much of an issue.

The actual issue would likely be that we make use of libgdiplus in various places. (Loading PNG textures, maps, timetables etc)
Something would also need to be done with on-screen controls etc

This isn't a priority for me, but it's by no means impossible either.

**Comment by Saikatsaha1996** [comment]
> Well, OpenTK supports Android natively. (Xamarin.Android is a fork of an early OpenTK version fwiw)
> 
> The current GL3.2 implementation is pretty simple too, so ES shouldn't be too much of an issue.
> 
> The actual issue would likely be that we make use of libgdiplus in various places. (Loading PNG textures, maps, timetables etc) Something would also need to be done with on-screen controls etc
> 
> This isn't a priority for me, but it's by no means impossible either.

Yes Sir for android application requires too many extra work.. actually personally i am railways fan.. that's why i am asking for openBVE as apk .. 

I also tried with wine.. not opening exe.. that's why asking for android platform.. and i believe if we get OpenBVE for android platform we can get raw performance with it..

**Comment by Saikatsaha1996** [comment]
> Well, OpenTK supports Android natively. (Xamarin.Android is a fork of an early OpenTK version fwiw)
> 
> The current GL3.2 implementation is pretty simple too, so ES shouldn't be too much of an issue.
> 
> The actual issue would likely be that we make use of libgdiplus in various places. (Loading PNG textures, maps, timetables etc) Something would also need to be done with on-screen controls etc
> 
> This isn't a priority for me, but it's by no means impossible either.

Os Android..
Emulator wine 8.2 staging tkg

I don't have any routes installed in OpenBVE 
But traineditor.exe opening but OpenBVE exe not opening.. any dependency is missing? I have .NET & C++ installed.. 
![Screenshot_2023-05-01-14-49-55-97_682db042e245bdfe41a756ea434d7a9e](https://user-images.githubusercontent.com/72664192/235434319-55d3f563-4996-4149-a78d-b9eff7c17833.jpg)

**Comment by Saikatsaha1996** [comment]
> Not sure I'm afraid. If anything the main menu ought to work seeing as you've got another Winform opening OK.... @ginga81 has OpenBVE running under WINE, but that's on Linux not Android.
> 
> See if the Object Viewer or Route Viewer work, and that'll tell us if it's the main menu or something more fundamental broken.

Not checked with vanilla wine it actually wine 8.2 staging tkg.. mey be issue this..

Actually i am sharing it because i hope  Android will work directly with OpenBVE apk (application)

**Comment by ginga81** [comment]
I think your feelings and enthusiasm were conveyed very well.

First of all, I would like to share our knowledge, but do you know that you know that Android is a mobile OS, and ARM was not designed to operate in the same way as a PC, but is designed to save power consumption, for example, smartphones.

You also know that Linux based Android's executables are JAVA, not Linux binaries, right?
Raspberry Pi is indeed ARM. But even though you yourself say the OS is Linux, if you run Linux binaries on Linux on ARM, it will work.
However, the person in the video that he should have rebuilt for ARM, is it?

Since Wine was released on Android in 2022, have there been any reports of not only OpenBVE but running MS-Office or Steam games?
I have never heard of it.

If you don't care so much about smartphones, I think you'd be better off just playing on a IntelCPU's Chromebook or SteamDeck now.
But, even if Chromebook takes 15 minutes to load without TFO or OuterView.
Even if OpenBVE works on Android, remember that even Chromebooks take 15 minutes to load.
Driver's view only, fps is a bit good such as my screenshot.

Completely unrelated, but SteamDeck is so good that I can't let it go as a gaming PC.(^^ゞ

Chromebook
![Screenshot 2021-05-30 16 12 20](https://user-images.githubusercontent.com/22734699/235597576-b11fdb13-b413-47af-83e5-e677321a7039.png)

SteamDeck
![SteamDeckでOpenBVE](https://user-images.githubusercontent.com/22734699/235597630-5d2dfaca-d6e9-4fce-b787-ef698703df79.jpg)

**Comment by Saikatsaha1996** [comment]
> I think your feelings and enthusiasm were conveyed very well.
> 
> First of all, I would like to share our knowledge, but do you know that you know that Android is a mobile OS, and ARM was not designed to operate in the same way as a PC, but is designed to save power consumption, for example, smartphones.
> 
> You also know that Linux based Android's executables are JAVA, not Linux binaries, right? Raspberry Pi is indeed ARM. But even though you yourself say the OS is Linux, if you run Linux binaries on Linux on ARM, it will work. However, the person in the video that he should have rebuilt for ARM, is it?
> 
> Since Wine was released on Android in 2022, have there been any reports of not only OpenBVE but running MS-Office or Steam games? I have never heard of it.
> 
> If you don't care so much about smartphones, I think you'd be better off just playing on a IntelCPU's Chromebook or SteamDeck now. But, even if Chromebook takes 15 minutes to load without TFO or OuterView. Even if OpenBVE works on Android, remember that even Chromebooks take 15 minutes to load. Driver's view only, fps is a bit good such as my screenshot.
> 
> Completely unrelated, but SteamDeck is so good that I can't let it go as a gaming PC.(^^ゞ
> 
> Chromebook ![Screenshot 2021-05-30 16 12 20](https://user-images.githubusercontent.com/22734699/235597576-b11fdb13-b413-47af-83e5-e677321a7039.png)
> 
> SteamDeck ![SteamDeckでOpenBVE](https://user-images.githubusercontent.com/22734699/235597630-5d2dfaca-d6e9-4fce-b787-ef698703df79.jpg)

Thank you for your response..

Actually i am also thinking about it to buy..

https://www.indiegogo.com/projects/aokzoe-a1pro-world-s-1st-7840u-gaming-handheld#/

Aokzoe 1 pro.. 

Now i am ready to play 😁

**Comment by Saikatsaha1996** [comment]
Update I bought Asus Rog Ally.. it's awesome handheld..

And even I also successfully installed OpenBve Train simulator in my Android via emulator.. 
![Screenshot_2024-01-03-03-15-21-45_b6022cb7d1a61f21e4fe914c8728a54c](https://github.com/leezer3/OpenBVE/assets/72664192/d34c8413-75bc-4452-8419-f1a7976bfa85)

But unfortunately I unable to start
my emulator resolution 1024x768
![Screenshot_2024-01-03-03-12-57-57_b6022cb7d1a61f21e4fe914c8728a54c](https://github.com/leezer3/OpenBVE/assets/72664192/630d492a-1363-43b6-b416-aa66ccf7afee)

I am closing this issue.. because it's not related with windows.. but I want to discuss.. 

Thank you
