### ISSUE TITLE
[Suggestion] Train Editor Update and new sound features.

### ISSUE THREAD

**Issue by NeXuSTrain** [leezer3/OpenBVE#92]
Hi to all. I've been developing EMU's for OpenBVE for quite a while now, and there is a feature that it doesn't have: **Continuous motor sounds**. What i'm talking about is a feature where the motor sounds will still play even if the combined-throttle is at neutral. Most EMUs in real-life have a sounding motor even when no power or no brake is applied. I was wondering if there is possible to make this feature available, and to be added to Train Editor as a checkbox to let train developers choose whether to have a sounding motor when no brake or power is applied or not. Also, it would be nice if Train Editor and OpenBVE would allow more than 2 sounds to be played simultaneously on power or brake so that we can create even more realistic motor sounds.

**Comment by leezer3** [comment]
Can I ask what **exact** behaviour you're after with the motor sounds?

I'll try and explain myself; Take a train travelling at 60km/h-
Should the motor sound for *Neutral* be played at the same pitch and volume as when the train is stationary, or does it require a speed and pitch change?
(This probably depends on the train and transmission type, but I'd like to know along which lines you're thinking.....)
Further, should the motor sound play even when the reverser is in neutral, or only when a direction is selected?

Gets complicated very fast!

A single static sound played whenever the power notch is at zero is easy enough, but anything else gets a lot more complicated.

Adding additional motor sounds to the train.dat (e.g. **MotorP3** , **MotorP4** etc.) is also relatively easy, but I'm not at all sure this is the best method of doing things.

The first and most important problem I see with this is that motor sounds are currently only speed and acceleration dependant, rather than allowing for things such as engine revs (I've made a passable RPM dependent model using a plugin here, although it's basic: https://github.com/leezer3/bvec_ats/blob/master/Traction/Diesel/Western.cs#L1000 ) & gears.

I've stated this before- Any changes I make to the default formats are working around limitations in 10+ year old stuff, and each change is likely to increase the chance of this stuff crashing older versions of openBVE, rather than just producing some harmless error messages.

A fully XML based train configuration is on my list of stuff that's in the pipeline, but no idea when.


Whilst I know this has turned into somewhat of a diverging ramble, opinions are always appreciated from someone who's actually hitting the limitations of what's currently possible.

**Comment by NeXuSTrain** [comment]
Thank you for your response!
As you stated in the first part, the motor sounds should be played continuously **only if a direction is set and no power nor brake is applied**. 
As for the pitch and volume, i would say that the pitch should depend on the speed of the train(for example, i am coasting at 60 km/h and there is a slight slope that makes my train increase it's speed. the pitch of the motor sounds should follow the graph that is in Train Editor) and only the volume should be slightly lowered.

**Comment by leezer3** [comment]
Basically what I thought.

My instinct is that for compatibility and ease of coding this will have to wait for the planned replacement of the train.dat format, and hence is a rather longer-term goal.

Some further technical / implementation thoughts:
* The current train.dat format requires a quite ridiculous setting of sound paramaters for every .2km/h - This should be replaced with adding appropriate set points, and then either linear interpolation or an interpolation curve to cut down on the cruft. IIRC the train editor already does a lot of this work internally, so the code could probably be hijacked.
* An unlimited number of motor and brake sounds are desirable.
* The volume of each motor/ brake soundset should have the option to be affected by the acceleration output or not. (Currently, the volume is proportional to the amount of acceleration being applied versus the theoretical maximum at the current speed)

**Comment by MarcRiera** [comment]
I have noticed that BVE5 already fixes some of these problems. There are four files where motor sounds are defined, two for power and two for brakes. One defines the volume and the other the pitch. Each line follows this pattern:

Speed, Volume/Pitch for sound 1, Volume/Pitch for sound 2, ..., Volume/Pitch for sound n

A line may have as many arguments as desired, so unlimited simultaneous sounds are possible. The values are also interpolated between speeds, so it becomes easier to code trains. Maybe this could be used as a starting point for the future new format.

**Comment by leezer3** [comment]
Not sure :)
My instinct tells me that each sound should be in either a separate section, or probably preferably a separate file.
Something like this structure:
```
Root train consist file
       Train performance data file
       Sound configuration file
            Motor & brake sound configuration files
```
Seems horribly confusing to have a massive number of potential sounds on one line if you're trying to troubleshoot one.

This commit adds basic Cosine interpolation for the API **Color24** and **Vector3** types, as I've been working on brightness interpolation:
https://github.com/leezer3/OpenBVE/commit/50379271118e1b804483c25f22e78db4cbe92a3d

(See this branch for the brightness code, although I'm not entirely happy with the XML structures, or tested as much as I'd like yet: https://github.com/leezer3/OpenBVE/tree/DynamicLight )
When we're sure this works, the same basic stuff needs adding to the rest of the API types, and then I'll need to think about the best way to extend the **double** and **int** types. 
Something like the BVE5 trim function will probably be the appropriate way to go with that.

More complex interpolation can easily be added using this pattern as necessary.

**Comment by leezer3** [comment]
A sample XML along the lines I'm thinking:
```XML
<?xml version="1.0" encoding="utf-8"?>
<openBVE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<MotorSoundTable>
    <TableEntry>
        <InterpolationMode>Cosine</InterpolationMode>
        <Speed>25</Speed>
        <Volume>1.0</Volume>
        <Pitch>1.0</Pitch>
    </TableEntry>
    <TableEntry>
        <InterpolationMode>Linear</InterpolationMode>
        <Speed>50</Speed>
        <Volume>2.0</Volume>
        <Pitch>0.5</Pitch>
    </TableEntry>
    <TableEntry>
        <Speed>100</Speed>
        <Volume>2.0</Volume>
        <Pitch>0.5</Pitch>
    </TableEntry>
</MotorSoundTable>
</openBVE>
```
This one would start playing the sound at 25km/h , and use Cosine interpolation upto 50km/h.
From 50km/h to 100km/h, linear interpolation would be used.
Finally, the sound stops at 100km/h

Thoughts?

**Comment by MarcRiera** [comment]
Looks good, I like the idea of having separate XML files for each sound. I think everything looks more intuitive than a line full of random numbers.

The current train format behaviour is to play the last sound definition if the maximum defined speed is reached, probably to make coding easier, but stopping the sound may be more clever now. If anyone needed a sound to play beyond the maximum speed, it would be as simple as adding a table entry for 500km/h or so with the same volume and pitch as the previous one.

**Comment by afarlie** [comment]
How does OpenRails implement the MSTS sound model?

**Comment by NeXuSTrain** [comment]
I forgot to mention it, but it would be nice if a "test" feature is also implemented. What i mean is to implement a player where you can test the motor sounds all together at a set speed from 0 km/h to the maximum speed of the train. It would make the motor sound testing much easier because in the current state of the simulator we must enter a route every time we want to test the sounds and the rolling sounds and other sounds like the idle, points and so on are in the way. 
Also, the horn sound mechanism should be updated, containing a starting sound, a looping sound and an ending sound, just like the compressor sound.
I have many ideas and i apologize if i am too "nosy" but i don't have the programming skills to do it so i only come with ideas. Thank you!
