### ISSUE TITLE
Some minor questions regarding this project

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#935]
These are just several (picky) questions that I'd like to know regarding this project, no big deal.

### Continuation or Fork?
openBVE was originally developed by michelle before it was discontinued in the 1.4 era, and this project is technically a fork of the original openBVE program ported to OpenTK, but at the same time it seems to be the only active fork, it continues from the v1.4 version number, and it retains the OpenBVE name (For the most part, minus the casing).

I've seen various user-editable sites (Like Wikipedia or Wine Database) where both of them are mixed up together. (Casing changed but content only refers to the michelle era, stating the discontinuation but versions from this port are referred afterwards, or they are treated as one single project).

I am curious as to how this should be addressed. Should this be considered as a direct continuation of openBVE, or should this be considered as a separate fork with it's own page?

### Icons
I've noticed there are two icons in the main program, one is with the white to black gradient and the other one is a flat one, and both are stated to be made by michelle.

![image](https://github.com/leezer3/OpenBVE/assets/28094366/264a8661-2216-459e-8c87-1a91c8d3f20d)

There's additionally another one (icon.bmp) shipped in the Data folder with a slightly different font and a tilted "e", not sure if that's ever used however.
![](https://raw.githubusercontent.com/leezer3/OpenBVE/master/assets/icon.bmp)

Is there any preference as to which one should be used?

### History
As far as I am aware the last release by michelle is v1.4.1.2, is this port worked from the original v1.4.1.2 release or based on another fork?
Thanks.

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/issues/305
Continuation or fork is a dangerous question.....

To cut a (very) long story short, all the original 4 dropped off the radar, probably c. 2005 or so after some pretty bitter community fallings out I'm not going into..... 
Michelle was first, Odaykufan lasted about another year or so, and was contactable after that but somewhat rude / dismissive about actually posting the thing again or keeping things alive. 

A discussion was had in the community when the project I initially started began to gain traction, and with a couple of the original other contributers to this (Mauricio M. Gavioli, Connor Fitzgerald) as to exactly how to proceed, and we decided that due to the small size of the community, keeping the name was preferable with no interest from the original creators. 
I think everyone involved would probably prefer to completely re-licence to BSD-2 (which I suppose might then be the formal fork), but as per the issue linked above things are a convoluted mess, and actually trying to unpick it has never been important enough to do formally, especially if someone wants to try and argue the point.

I believe (although I stand to be corrected) that the codebase was originally Odaykufan's last version. which should be v1.4.3
As far as I remember, this has no practical changes from Michelle's last version, other than removing her original managed content system.

---

Logo-
The gradient based one was original.
Then the fad for flattening icons came along. I'm not quite sure whether this is Michelle's or later (memory says somewhere around the release of Windows 8, but that's fallible); the SVG originates here:
https://github.com/leezer3/OpenBVE/commits/c0795f40f4102e15541757b824ca7c94ef506014/VectorImageSources/logo_icon.svg?browsing_rename_history=true&new_path=graphics/logo_icon.svg&original_branch=master

The flat one with non-sloped e is 'current'
The tilted e was tweaked to be less like Mackoy's BVE logo, but most of the Japanese social nuances on that one went somewhat over my head.
