### ISSUE TITLE
[Question or bug?] Densha de GO TYPE-2 controller can't set P5

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#952]
### Description

Connect Densha de GO TYPE-2 controller.
Run OpenBVE, and setting for input device plugin for Densha de Go.
don't check Handle mapping's 'Convert notches'.
Play sample route and using with same data's train.
Even we set to P5, we can't set P5 and notch is N.
When we set to Convert notches and Keep minimum and maximum options, we can set to P5, and show obey these options.
This phenomenon occurs on my Ubuntu 20.04 and the reporting user's Windows 10.
I am unable to determine whether this phenomenon is a plug-in specification or a bug.
I would appreciate it if someone could answer.
Regards

## Train
use
https://github.com/leezer3/OpenBVE/issues/614

## Logs

This issue didn't crash. So no log.

### Related information 

My PC's spec:
OS:Ubuntu 20.04 LTS 64bit
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Memory:31.3GB
Graphic:AMD Radeon RX 590 Series (POLARIS10, DRM 3.40.0, 5.11.0-40-generic, LLVM 12.0.0)

Reported user's spec
OS:Windows 10 Home 22H2 build19045.3570

Controller:both environment
Densha de GO controller TYPE-2 for PlayStation 2

**Comment by leezer3** [comment]
@MarcRiera 
I don't have one of these, but it sounds to me like it needs the convert notches selected, and isn't really a bug. (UI bug maybe?)

**Comment by MarcRiera** [comment]
There is definitely something broken, because 1.9.1.2 seems to be the last version with a fully working plugin. Starting from 1.9.2.2, the brake/power handles are not updated in-game and only the buttons work. My guess: it may be related to the addition of uncoupling in that version (@leezer3 I remember reading about possible side effects on input device plugins). I will need to have a look in detail.

@ginga81 Just to confirm the expected behaviour with a working plugin: with "Convert notches" disabled, everything is mapped 1:1. For example, P4 in the controller equals P4 in the train and B7 equals B7 in the train. If the train has more notches than the controller, these notches are unreachable. With "Convert notches" enabled, the train's notches are distributed to the controller's notches. This way, for example, it is possible to use a P1-P8 train with a controller having only P1-P5 (many notches are skipped in this mode).

**Comment by ginga81** [comment]
I see.
That means that the sample train only has up to 4 notches, so P5 does not exist, so it becomes N, right?
Of course, if we press the option, it will be distributed and we have confirmed that it works.

**Comment by MarcRiera** [comment]
> I see. That means that the sample train only has up to 4 notches, so P5 does not exist, so it becomes N, right? Of course, if we press the option, it will be distributed and we have confirmed that it works.

In that case, if the train only has 4 notches but the controller has 5, P5 should become P4, not N. That sounds like a bug, I will see if it is fixed after I get anything working on my side. 

> According to the user who reported it, if we set the maximum notch of Train to P6 and check 'Convert notches', there will be only 2 stages in total, and the number of stages in the middle will not be allocated. I think this is too minimum, so I think it should be assign a middle notch. What do you think about?

That is also unexpected and a bug, probably the same as above.

**Comment by leezer3** [comment]
I can't see anything that would immediately cause issues with input device plugins- Nothing has really been touched with regards to control handles etc.

Stepping it in the debugger, the values passed on the SetVehicleSpecs and Elapse calls both appear sensible and consistant with prior versions, which is where I'd have thought any issues would arise if it was uncoupling related (most of the issues here came with things that stored a fixed train length at the start of the game)
I can also follow it through the logic tree of applying power / brake which appears OK.

Unfortunately, it's a PITA to try and debug without one of these with the funkyness they use....
This feels as if we've got two different issues at play here.
I'm not sure that @MarcRiera your brake / power not working is related. Controller adaptor issue or something maybe?

**Comment by MarcRiera** [comment]
Just tested on Windows, where the plugin fully works. @ginga81 I can see the issue, the notches do not match at all in some cases. I will check that part of the code.

@leezer3 My issue on Linux is very strange and does not seem related to a specific controller. It happens regardless of whether it is a PS1 controller via adaptor, a PS2 USB controller or a PC HID controller. Given that Ubuntu 20.04 works, and that the two PCs where I have run tests have up-to-date Arch Linux, I begin to suspect it may be an Arch-specific problem. I will take a look at it once the notch mapping bug is fixed.

**Comment by MarcRiera** [comment]
@ginga81 I checked the code and found an off-by-one error. The last notch of the power handle was never mapped when "Convert notches" was enabled, regardless of the controller model. Now, on a train with 4 power notches and a controller with 5 notches, the mapping will be N-P1-P2-P3-P4-P4 instead of N-P1-P2-P3-P4-N.

**Comment by ginga81** [comment]
When the user who reported it went to check it, he reported that when it was set to P6, the behavior was only in two stages as before.
Is this true?
If so, I think that should fix it.

**Comment by MarcRiera** [comment]
> When the user who reported it went to check it, he reported that when it was set to P6, the behavior was only in two stages as before. Is this true? If so, I think that should fix it.

The fix is already in the latest build, so he can test it easily: https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2023-11-02.zip

I ran many tests and everything seemed to be mapped correctly with any combination of options. If the bug is still there, please let me know. Thank you!
